### ISSUE TITLE
[ENHANCEMENT]: Prettify err in case the supplied flag(s) is/are unknown

### ISSUE THREAD

**Issue by anshumanv** [webpack/webpack-cli#1046]
**Describe the bug**
Presently thrown err are simply logged in case of unknown flag, maybe we can present it nicely and show a message to use help flag for proper usage

**What is the current behavior?**
Stacktrace is printed in case of unknown flag.

**To Reproduce**
Invoke cli with an unknown flag

**Expected behavior**
concise message of supplying an unknown flag should be displayed. something like - 
![image](https://user-images.githubusercontent.com/21009455/63222738-241d5480-c1c9-11e9-8cc6-0834cb7412aa.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/21009455/63222699-b07b4780-c1c8-11e9-9c83-b7f1e7f72b6f.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Looking for feedback on this before starting work.

**Comment by anshumanv** [comment]
@evenstensberg @ematipico @rishabh3112 thoughts are appreciated. 😄

**Comment by evenstensberg** [comment]
Yep we definitely need to do this

**Comment by anshumanv** [comment]
On it then!

**Comment by evenstensberg** [comment]
baller af

**Comment by jamesgeorge007** [comment]
```bash
➜  webpack-cli git:(next) webpack-cli --init
⬢ webpack: Unknown argument: --init

 Compilation Results

 Version: 5.0.0-beta.12
 Built: Thu Jan 23 2020 21:39:54 GMT+0530 (India Standard Time)
 Compile Time: 186ms
 Output Directory: /home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/dist

┌────────────────────┬─────────────────────────────────────────────┬───────────────┐
│ Bundle emitted     │ Bundle name                                 │ Bundle size   │
├────────────────────┼─────────────────────────────────────────────┼───────────────┤
│ failed             │ main.js                                     │ 0.00 kb       │
└────────────────────┴─────────────────────────────────────────────┴───────────────┘

⬢ webpack: configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

⬢ webpack: NoModeWarning: configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
    at /home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/WarnNoModeSetPlugin.js:20:30
    at Hook.eval [as call] (eval at create (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at Hook.CALL_DELEGATE [as _call] (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/Compiler.js:857:30)
    at /home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/Compiler.js:898:29
    at Hook.eval [as callAsync] (eval at create (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/Compiler.js:893:28)
    at /home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/Compiler.js:424:12
    at Compiler.readRecords (/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli/node_modules/webpack/lib/Compiler.js:736:11)


⬢ webpack: Module not found: Error: Can't resolve './src' in '/home/james-the-hacker/CodeSpace/GitHub-Projects/webpack-cli'
```

**Comment by jamesgeorge007** [comment]
\cc @ematipico

**Comment by ematipico** [comment]
@jamesgeorge007  could you please argument your comment? I don't understand why the comment 😅

**Comment by jamesgeorge007** [comment]
Oops!

**Comment by jamesgeorge007** [comment]
Passing in an unknown flag results in the logs as given above in my case. We can avoid those unnecessary logs by performing an exit here:-
https://github.com/webpack/webpack-cli/blob/a0ac134ff0d0a17c10387da99f5e96443e48bb15/lib/bootstrap.js#L70

**Comment by anshumanv** [comment]
What about passing a valid flag then an unvalid flag?

**Comment by anshumanv** [comment]
I think we can execute for the valid flag and log about the other parameter being invalid.

**Comment by anshumanv** [comment]
Can do whatever everyone agrees with. ✨
