### ISSUE TITLE
[BUG]: TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by ohana54** [webpack/webpack-cli#1089]
(Context: https://github.com/webpack/webpack-cli/pull/1088#pullrequestreview-296451308)

**Describe the bug**

The migrate failed with the following message:
```
TypeError: Cannot read property 'push' of undefined
    at NodePath.ast_utils_1.findPluginsByName.forEach (./webpack-cli/packages/migrate/uglifyJsPlugin/uglifyJsPlugin.js:68:41)
    at __paths.forEach (./webpack-cli/packages/migrate/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (./webpack-cli/packages/migrate/node_modules/jscodeshift/src/Collection.js:76:18)
    at default_1 (./webpack-cli/packages/migrate/uglifyJsPlugin/uglifyJsPlugin.js:31:71)
    at Timeout.setTimeout [as _onTimeout] (./webpack-cli/packages/migrate/migrate.js:42:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**To Reproduce**
```
>npx webpack-cli migrate webpack.config.js
```

Example webpack.config.js:
```js
var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
var path = require("path")
var WWW_DIR = path.resolve(__dirname, 'wwwroot');

module.exports = {
    context: __dirname,
    devtool: debug ? "inline-sourcemap" : false,
    entry: "./wwwroot/js/scripts.jsx",
    output: {
        path: __dirname + "/wwwroot/js",
        filename: "scripts.min.js"
    },
    module: {
        loaders: [{
                test: /\.js?/,
                loader: "babel-loader",
                query: {
                    presets: ["react", "es2015", "stage-2"]
                }
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            }
        ]
    },
    resolve: {
        extensions: ['.js', '.jsx']
    },
    plugins: debug ? [] : [
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("production")
            }
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.UglifyJsPlugin({ parallel: true, mangle: true, sourcemap: false }),
    ],
};
```

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: macOS High Sierra 10.13.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.11.3 - /var/folders/mh/_2j629nj7tdcxfhfqdjb89fm0000gn/T/fnm-shell-9197667/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /var/folders/mh/_2j629nj7tdcxfhfqdjb89fm0000gn/T/fnm-shell-9197667/bin/npm
  Browsers:
    Safari: 11.1
  npmGlobalPackages:
    webpack-cli: 3.3.9
```

**Comment by ohana54** [comment]
This happens because of the condition in setting the plugins.
The condition creates an extra nesting level in the AST, causing this line to be incorrect (we need to go 4 parents up): https://github.com/webpack/webpack-cli/blob/b46efe609ce7f3754b5c4efd7c866a2a29aad5e2/packages/migrate/uglifyJsPlugin/uglifyJsPlugin.ts#L46

I thought maybe traverse until we reach an `ObjectExpression` node, but webpack config can also be an array, function or promise.
An alternative can be to traverse until we reach the `plugins` property node, and from there go up 1 more parent.

BTW, adding conditions in other places in the config messes up the migrated config generation, for example the `devtool` property is generated with an empty value.

Thoughts?

**Comment by ohana54** [comment]
Tried with latest versions and got:
```
 ✖ ︎Migration aborted due to some errors:

TypeError: Cannot create property 'context' on string 'Error generating AST'
    at /Users/user/project/node_modules/listr/index.js:112:19
  ✖ Reading webpack config
```

**Comment by anshumanv** [comment]
bump

**Comment by alexander-akait** [comment]
I think we can close this, because migrate is deprecated and will be removed in the next major release (also it is not part of the default installation), so no need to focus on it, instead we should focused on `init`, also many migrations are impossible due complex changes
