### ISSUE TITLE
Feedback using with webpack 5 beta

### ISSUE THREAD

**Issue by marcins** [webpack/webpack-cli#1117]
I'm playing around with the current HEAD of the `next` branch, and Webpack 5 beta 5, and so far have two pieces of feedback. Not sure if you actually want them yet, but here they are anyway!

1. output with `--progress` is not very verbose, it basically said "10% building" for 3-4 minutes (how long it takes) and then the rest. Maybe there's just a `--verbose` flag I haven't found yet, but the old CLI would show some bundling progress.

2. more importantly, the way warnings render lose a lot of context. Our component library is using default imports from JSON in most components - this isn't supported in Webpack 5 and this results in a _lot_ of warnings. With the "old" CLI I'd get the raw warnings, which contained info about where the warning was coming from:

```
⚠webpack:  {
  moduleIdentifier: '/Users/mszczepanski/Work/REDACTED/node_modules/thread-loader/dist/cjs.js??ruleSet[1].rules[0].use[0]!/Users/mszczepanski/Work/REDACTED/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].use[1]!/Users/mszczepanski/Work/REDACTED/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[7]!/Users/mszczepanski/Work/REDACTED/node_modules/@REDACTED/REDACTED/node_modules/@REDACTED/tag/dist/esm/Tag/index.js',
  moduleName: './node_modules/REDACTED/node_modules/@REDACTED/tag/dist/esm/Tag/index.js',
  loc: '149:18-32',
  message: "Can't import the named export 'version' (imported as 'packageVersion') from JSON module (only default export is available)",
  moduleId: './node_modules/REDACTED/node_modules/@REDACTED/tag/dist/esm/Tag/index.js',
  moduleTrace: [ /* ... etc */

```

However with the new CLI I only get the warning, the stack, but no context for the warning:

```
⬢ webpack: Can't import the named export 'name' (imported as 'packageName') from JSON module (only default export is available)

⬢ webpack: ModuleDependencyWarning: Can't import the named export 'name' (imported as 'packageName') from JSON module (only default export is available)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/Compilation.js:1642:23)
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/Compilation.js:1404:10
    at _next1 (eval at create (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/neo-async/async.js:2850:39)
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:219:18
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/neo-async/async.js:2830:7
    at done (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/neo-async/async.js:2865:11)
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/neo-async/async.js:2818:7
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:67:11
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/Cache.js:77:6
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/Cache.js:34:11
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/cache/IdleFileCachePlugin.js:63:8
    at /Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/lib/Cache.js:80:6
    at eval (eval at create (/Users/mszczepanski/Work/ecosystem/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
```

**Comment by evenstensberg** [comment]
Thx for the feedback! If you have any more, preferences or anything, feel free to speak up!
