### ISSUE TITLE
[Bug]: Error logs after running cli 

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#1137]
**Describe the bug**
After running a successful command long error logs appears.
```
 Compilation Results

 Version: 5.0.0-beta.3
 Built: Sat Dec 07 2019 00:14:42 GMT+0530 (India Standard Time)
 Compile Time: 159ms
 Output Directory: /home/undefined/OSS/webpack/webpack-test/dist

┌───────────────┬─────────────────────────────────────────────┬───────────────┐
│ Build Status  │ Bundle Name                                 │ Bundle Size   │
├───────────────┼─────────────────────────────────────────────┼───────────────┤
│ failed        │ main.js                                     │ 0 kb          │
└───────────────┴─────────────────────────────────────────────┴───────────────┘

⬢ webpack: configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

⬢ webpack: NoModeWarning: configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
    at /home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/WarnNoModeSetPlugin.js:20:30
    at Hook.eval [as call] (eval at create (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at Hook.CALL_DELEGATE [as _call] (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:851:30)
    at /home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:892:29
    at Hook.eval [as callAsync] (eval at create (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:887:28)
    at /home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:420:12
    at Compiler.readRecords (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:732:11)
    at /home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:417:11
    at Hook.eval [as callAsync] (eval at create (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/lib/Compiler.js:414:20
    at Hook.eval [as callAsync] (eval at create (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/undefined/OSS/webpack/webpack-cli/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)


```

**What is the current behavior?**
Long error logs

**To Reproduce**
1. Run `webpack-cli --config webpack.config.js`

**Expected behavior**
No err logs
**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by jamesgeorge007** [comment]
Fixed in #1196
