### ISSUE TITLE
Test Error : "Package Manager should spawn npm update from spawnchild" when building using Yarn

### ISSUE THREAD

**Issue by parulc7** [webpack/webpack-cli#1160]
**Describe the bug**

After bootstrapping and building using yarn, I ran the package tests and it returned the erro - **Package manager should spawn npm update from spawnchild**

**What is the current behavior?**
```

 ✘ pc@pc-HP-Pavilion-Notebook  ~/Desktop/webpack-cli   next ✚  yarn test:packages                                            
yarn run v1.21.1
$ nyc jest packages/ --maxWorkers=4 --reporters=default --reporters=jest-junit
 PASS  packages/migrate/commonsChunkPlugin/__tests__/commonsChunkPlugin.test.ts
 PASS  packages/generators/__tests__/loader-generator.test.ts
 PASS  packages/utils/__tests__/ast-utils.test.ts
 PASS  packages/migrate/__tests__/migrate.test.ts
 PASS  packages/utils/__tests__/recursive-parser.test.ts
 PASS  packages/migrate/uglifyJsPlugin/__tests__/uglifyJsPlugin.test.ts
 PASS  packages/migrate/loaders/__tests__/loaders.test.ts
 PASS  packages/migrate/moduleConcatenationPlugin/__tests__/moduleConcatenationPlugin.test.ts
 PASS  packages/info/__tests__/index.test.ts

Please remove deprecated plugins manually. 
See https://webpack.js.org/guides/migrating/ for more information.
Please remove deprecated plugins manually. 
See https://webpack.js.org/guides/migrating/ for more information.
Please remove deprecated plugins manually. 
 PASS  packages/migrate/removeDeprecatedPlugins/__tests__/removeDeprecatedPlugins.test.ts
 PASS  packages/migrate/loaderOptionsPlugin/__tests__/loaderOptionsPlugin.test.ts
 PASS  packages/generators/__tests__/add-generator.test.ts
 PASS  packages/migrate/outputPath/__tests__/outputPath.test.ts
 PASS  packages/webpack-scaffold/__tests__/index.test.ts
 PASS  packages/migrate/extractTextPlugin/__tests__/extractTextPlugin.test.ts
 PASS  packages/utils/__tests__/npm-exists.test.ts
 PASS  packages/migrate/removeJsonLoader/__tests__/removeJsonLoader.test.ts
 PASS  packages/migrate/resolve/__tests__/resolve.test.ts
 PASS  packages/migrate/bannerPlugin/__tests__/bannerPlugin.test.ts
 PASS  packages/migrate/noEmitOnErrorsPlugin/__tests__/noEmitOnErrorsPlugin.test.ts
 PASS  packages/migrate/namedModulesPlugin/__tests__/namedModulesPlugin.test.ts
 PASS  packages/utils/__tests__/is-local-path.test.ts
 PASS  packages/utils/__tests__/resolve-packages.test.ts
 PASS  packages/utils/__tests__/validate-identifier.test.ts
 FAIL  packages/utils/__tests__/package-manager.test.ts (6.526s)
  ● package-manager › should spawn npm update from spawnChild

    expect(jest.fn()).toHaveBeenLastCalledWith(...expected)

    Expected: "npm", ["update", "-g", "some-pkg"], {"stdio": "inherit"}
    Received
           7: "npm", ["install", "-g", "some-pkg"], {"stdio": "inherit"}
    ->     8
              undefined,
              Array [
            -   "update",
            -   "-g",
            +   "global",
            +   "add",
                "some-pkg",
              ],
              {"stdio": "inherit"},

    Number of calls: 8

      74 | 
      75 | 		packageManager.spawnChild(packageName);
    > 76 | 		expect(spawn.sync).toHaveBeenLastCalledWith("npm", ["update", "-g", packageName], { stdio: "inherit" });
         | 		                   ^
      77 | 	});
      78 | 
      79 | 	it("should return the npm global dir from getPathToGlobalPackages if yarn is not installed", () => {

      at Object.<anonymous> (packages/utils/__tests__/package-manager.test.ts:76:22)

 PASS  packages/utils/__tests__/npm-packages-exists.test.ts (7.208s)

Summary of all failing tests
 FAIL  packages/utils/__tests__/package-manager.test.ts (6.526s)
  ● package-manager › should spawn npm update from spawnChild

    expect(jest.fn()).toHaveBeenLastCalledWith(...expected)

    Expected: "npm", ["update", "-g", "some-pkg"], {"stdio": "inherit"}
    Received
           7: "npm", ["install", "-g", "some-pkg"], {"stdio": "inherit"}
    ->     8
              undefined,
              Array [
            -   "update",
            -   "-g",
            +   "global",
            +   "add",
                "some-pkg",
              ],
              {"stdio": "inherit"},

    Number of calls: 8

      74 | 
      75 | 		packageManager.spawnChild(packageName);
    > 76 | 		expect(spawn.sync).toHaveBeenLastCalledWith("npm", ["update", "-g", packageName], { stdio: "inherit" });
         | 		                   ^
      77 | 	});
      78 | 
      79 | 	it("should return the npm global dir from getPathToGlobalPackages if yarn is not installed", () => {

      at Object.<anonymous> (packages/utils/__tests__/package-manager.test.ts:76:22)


Test Suites: 1 failed, 25 passed, 26 total
Tests:       1 failed, 143 passed, 144 total
Snapshots:   95 passed, 95 total
Time:        8.393s
Ran all test suites matching /packages\//i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**To Reproduce**
1. yarn bootstrap
2. yarn build
3. yarn test:packages

**Expected behavior**

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
⬢ webpack: Promise rejection: TypeError: Cannot convert undefined or null to object
⬢ webpack: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Object.<anonymous> (/home/pc/Desktop/webpack-cli/node_modules/@webpack-cli/info/index.js:45:41)
    at Generator.next (<anonymous>)
    at /home/pc/Desktop/webpack-cli/node_modules/@webpack-cli/info/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pc/Desktop/webpack-cli/node_modules/@webpack-cli/info/index.js:4:12)
    at Object.info [as default] (/home/pc/Desktop/webpack-cli/node_modules/@webpack-cli/info/index.js:44:12)
    at Function.run (/home/pc/Desktop/webpack-cli/lib/commands/external.js:65:48)
    at WebpackCLI.runCommand (/home/pc/Desktop/webpack-cli/lib/webpack-cli.js:160:53)
    at runCLI (/home/pc/Desktop/webpack-cli/lib/bootstrap.js:59:26)

**Additional context**

**Comment by anshumanv** [comment]
Hey @Deathrow77 👋 

Can you try rebasing from master and running tests again to see if the problem persists?

**Comment by evilebottnawi** [comment]
Let's close, if you faces with the issue again, feel free to open a new issue or put feedback here, we have CLI tests and nobody has a problems with it, and I can't reproduce too
