### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [webpack/webpack-cli#1212]
**Describe the bug**

I'm using framework7 with webpack. I tried with create-react-app but error still persists

**What is the current behavior?**
When i run `npm start` and throws following error:-

  `internal/modules/cjs/loader.js:796
    throw err;
    ^
   Error: Cannot find module 'C:\Users\gagan\Projects\hybrid\reminder\build\webpack.config.js'
Require stack:
- C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WEBPACK_OPTIONS (C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at Object.<anonymous> (C:\Users\gagan\Projects\hybrid\reminder\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\gagan\\Projects\\hybrid\\reminder\\node_modules\\webpack-cli\\bin\\utils\\convert-argv.js',
    'C:\\Users\\gagan\\Projects\\hybrid\\reminder\\node_modules\\webpack-dev-server\\bin\\webpack-dev-server.js'
  ]
}`
Since this error is producing with framework7 as well as react it looks like there is some problem with webpack-cli rather than the frameworks.

**Expected behavior**
It should start serving the project

**Comment by rishabh3112** [comment]
Hi @GAGANsinghmsitece,
Please share a minimum reproducible repository for us to investigate.

**Comment by ematipico** [comment]
Most probably a similar issue of #1215

**Comment by ematipico** [comment]
This is fixed

**Comment by belmab** [comment]
What was the solution?
