### ISSUE TITLE
Bug: webpack-cli --verbose throws TypeError: Cannot set property 'stats' of undefined

### ISSUE THREAD

**Issue by aman29271** [webpack/webpack-cli#1443]
**Describe the bug**

**What is the current behavior?**
`webpack-cli --verbose` or `webpack-cli --verbose --stats verbose` throws an error described below.
```javascript
[webpack-cli] TypeError: Cannot set property 'stats' of undefined
    at StatsGroup.resolveOptions (/home/phoenix/Desktop/webpack-cli/packages/webpack-cli/lib/groups/StatsGroup.js:23:40)
    at StatsGroup.run (/home/phoenix/Desktop/webpack-cli/packages/webpack-cli/lib/groups/StatsGroup.js:33:14)
    at WebpackCLI._handleGroupHelper (/home/phoenix/Desktop/webpack-cli/packages/webpack-cli/lib/webpack-cli.js:220:40)
    at Promise.resolve.then.then.then.then.then.then.then (/home/phoenix/Desktop/webpack-cli/packages/webpack-cli/lib/webpack-cli.js:269:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

**To Reproduce**

Use either verbose flag or verbose flag with some value of stats flag. 

**Expected behavior**
Using verbose flags should output everything. If the verbose flag is used with stats flag then it should also output everything if the stats has a valid flag value else, it should also throw a warning if the stats flag value is not a valid one.

**Screenshots**
![Screenshot from 2020-04-11 18-56-15](https://user-images.githubusercontent.com/30979779/79044919-cf31c100-7c25-11ea-91fb-25ab3fe7ecd4.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```bash
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 693.40 MB / 7.66 GB
  Binaries:
    Node: 10.15.2 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 5.8.0 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 68.6.0esr
  npmPackages:
    webpack: ^4.42.0 => 5.0.0-beta.14 
    webpack-cli: ^3.3.11 => 4.0.0-beta.8 
```
**Additional context**

**Comment by anshumanv** [comment]
Known issue, being fixed here - https://github.com/webpack/webpack-cli/pull/1191

**Comment by aman29271** [comment]
That fix was for master. It's for next though.

**Comment by anshumanv** [comment]
Cool, nice work 👍

**Comment by aman29271** [comment]
cheers

**Comment by snitin315** [comment]
fixed in https://github.com/webpack/webpack-cli/pull/1549
