### ISSUE TITLE
[Bug] encounter "configuration[0].optimization has an unknown property 'namedModules'" error when use webpack-cli ^3.1.2 with webpack 5.x.beta x 

### ISSUE THREAD

**Issue by achenwei-chwy** [webpack/webpack-cli#1809]
**Describe the bug**
getting bug for namedModules invalid, but it suppose to be valid in webpack 5.x beta.

config extract below:
```
module.exports = {
  optimization: {
    namedModules: true,
    minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})]
  },
  entry: {...

```
**What is the current behavior?**
getting error like following:

```
.../node_modules/webpack-cli/bin/cli.js:281
[js]                            throw err;
[js]                            ^
[js] 
[js] ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
[js]  - configuration[0].optimization has an unknown property 'namedModules'. These properties are valid:
[js]    object { checkWasmTypes?, chunkIds?, concatenateModules?, emitOnErrors?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, realContentHash?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
```

**To Reproduce**
intall webpack 5.x and webpack-cli ^3.1.2 as well as add  similiar config above

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
[css] webpack is watching the files...
[css] 
[css] (node:20872) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
[css] <s> [webpack.Progress] 10% building import loader ./node_modules/mini-css-extract-plugin/dist/loader.js
[css] <s> [webpack.Progress] 10% building import loader ./node_modules/css-loader/dist/cjs.js
[js] /Users/achenwei/www/storefront/node_modules/webpack-cli/bin/cli.js:281
[js]                            throw err;
[js]                            ^
[js] 
[js] ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
[js]  - configuration[0].optimization has an unknown property 'namedModules'. These properties are valid:
[js]    object { checkWasmTypes?, chunkIds?, concatenateModules?, emitOnErrors?, flagIncludedChunks?, innerGraph?, mangleExports?, mangleWasmImports?, mergeDuplicateChunks?, minimize?, minimizer?, moduleIds?, noEmitOnErrors?, nodeEnv?, portableRecords?, providedExports?, realContentHash?, removeAvailableModules?, removeEmptyChunks?, runtimeChunk?, sideEffects?, splitChunks?, usedExports? }
[js]    -> Enables/Disables integrated optimizations.
[js]  - configuration[1].module.rules[6] has an unknown property 'loaders'. These properties are valid:
[js]    object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }
[js]    -> A rule description with conditions and effects for modules.
[js]     at validate (/Users/achenwei/www/storefront/node_modules/webpack/node_modules/schema-utils/dist/validate.js:98:11)
[js]     at validateSchema (/Users/achenwei/www/storefront/node_modules/webpack/lib/validateSchema.js:46:2)
[js]     at webpack (/Users/achenwei/www/storefront/node_modules/webpack/lib/webpack.js:100:2)
[js]     at f (/Users/achenwei/www/storefront/node_modules/webpack/lib/index.js:31:15)
[js]     at processOptions (/Users/achenwei/www/storefront/node_modules/webpack-cli/bin/cli.js:272:16)
[js]     at /Users/achenwei/www/storefront/node_modules/webpack-cli/bin/cli.js:364:3
[js]     at Object.parse (/Users/achenwei/www/storefront/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
[js]     at /Users/achenwei/www/storefront/node_modules/webpack-cli/bin/cli.js:49:8
[js]     at Object.<anonymous> (/Users/achenwei/www/storefront/node_modules/webpack-cli/bin/cli.js:366:3)
[js]     at Module._compile (internal/modules/cjs/loader.js:959:30)
[js]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[js]     at Module.load (internal/modules/cjs/loader.js:815:32)
[js]     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[js]     at Module.require (internal/modules/cjs/loader.js:852:19)
[js]     at require (internal/modules/cjs/helpers.js:74:18)
[js]     at Object.<anonymous> (/Users/achenwei/www/storefront/node_modules/webpack/bin/webpack.js:132:2)
[js]     at Module._compile (internal/modules/cjs/loader.js:959:30)
[js]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[js]     at Module.load (internal/modules/cjs/loader.js:815:32)
[js]     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[js]     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[js]     at internal/main/run_main_module.js:17:11 {
[js]   name: 'ValidationError',
[js]   errors: [
[js]     {
[js]       keyword: 'additionalProperties',
[js]       dataPath: '[0].optimization',
[js]       schemaPath: '#/additionalProperties',
[js]       params: [Object],
[js]       message: 'should NOT have additional properties',
[js]       schema: false,
[js]       parentSchema: [Object],
[js]       data: [Object]
[js]     },
[js]     {
[js]       keyword: 'oneOf',
[js]       dataPath: '[1].module.rules',
[js]       schemaPath: '#/properties/rules/oneOf',
[js]       params: [Object],
[js]       message: 'should match exactly one schema in oneOf',
[js]       schema: [Array],
[js]       parentSchema: [Object],
[js]       data: [Array],
[js]       children: [Array]
[js]     }
[js]   ],
[js]   schema: {
[js]     definitions: {
[js]       Amd: [Object],
[js]       AssetModuleFilename: [Object],
[js]       AuxiliaryComment: [Object],
[js]       Bail: [Object],
[js]       CacheOptions: [Object],
[js]       CacheOptionsNormalized: [Object],
[js]       Charset: [Object],
[js]       ChunkFilename: [Object],
[js]       ChunkFormat: [Object],
[js]       ChunkLoadTimeout: [Object],
[js]       ChunkLoading: [Object],
[js]       ChunkLoadingGlobal: [Object],
[js]       ChunkLoadingType: [Object],
[js]       CompareBeforeEmit: [Object],
[js]       Context: [Object],
[js]       CrossOriginLoading: [Object],
[js]       Dependencies: [Object],
[js]       DevServer: [Object],
[js]       DevTool: [Object],
[js]       DevtoolFallbackModuleFilenameTemplate: [Object],
[js]       DevtoolModuleFilenameTemplate: [Object],
[js]       DevtoolNamespace: [Object],
[js]       EnabledChunkLoadingTypes: [Object],
[js]       EnabledLibraryTypes: [Object],
[js]       EnabledWasmLoadingTypes: [Object],
[js]       Entry: [Object],
[js]       EntryDescription: [Object],
[js]       EntryDescriptionNormalized: [Object],
[js]       EntryDynamic: [Object],
[js]       EntryDynamicNormalized: [Object],
[js]       EntryItem: [Object],
[js]       EntryNormalized: [Object],
[js]       EntryObject: [Object],
[js]       EntryRuntime: [Object],
[js]       EntryStatic: [Object],
[js]       EntryStaticNormalized: [Object],
[js]       EntryUnnamed: [Object],
[js]       Environment: [Object],
[js]       Experiments: [Object],
[js]       ExternalItem: [Object],
[js]       Externals: [Object],
[js]       ExternalsPresets: [Object],
[js]       ExternalsType: [Object],
[js]       FileCacheOptions: [Object],
[js]       Filename: [Object],
[js]       FilterItemTypes: [Object],
[js]       FilterTypes: [Object],
[js]       GlobalObject: [Object],
[js]       HashDigest: [Object],
[js]       HashDigestLength: [Object],
[js]       HashFunction: [Object],
[js]       HashSalt: [Object],
[js]       HotUpdateChunkFilename: [Object],
[js]       HotUpdateGlobal: [Object],
[js]       HotUpdateMainFilename: [Object],
[js]       Iife: [Object],
[js]       ImportFunctionName: [Object],
[js]       InfrastructureLogging: [Object],
[js]       Library: [Object],
[js]       LibraryCustomUmdCommentObject: [Object],
[js]       LibraryCustomUmdObject: [Object],
[js]       LibraryExport: [Object],
[js]       LibraryName: [Object],
[js]       LibraryOptions: [Object],
[js]       LibraryType: [Object],
[js]       Loader: [Object],
[js]       MemoryCacheOptions: [Object],
[js]       Mode: [Object],
[js]       ModuleOptions: [Object],
[js]       Name: [Object],
[js]       Node: [Object],
[js]       NodeOptions: [Object],
[js]       Optimization: [Object],
[js]       OptimizationRuntimeChunk: [Object],
[js]       OptimizationRuntimeChunkNormalized: [Object],
[js]       OptimizationSplitChunksCacheGroup: [Object],
[js]       OptimizationSplitChunksGetCacheGroups: [Object],
[js]       OptimizationSplitChunksOptions: [Object],
[js]       OptimizationSplitChunksSizes: [Object],
[js]       Output: [Object],
[js]       OutputModule: [Object],
[js]       OutputNormalized: [Object],
[js]       Parallelism: [Object],
[js]       Path: [Object],
[js]       Pathinfo: [Object],
[js]       Performance: [Object],
[js]       PerformanceOptions: [Object],
[js]       Plugins: [Object],
[js]       Profile: [Object],
[js]       PublicPath: [Object],
[js]       RecordsInputPath: [Object],
[js]       RecordsOutputPath: [Object],
[js]       RecordsPath: [Object],
[js]       Resolve: [Object],
[js]       ResolveAlias: [Object],
[js]       ResolveLoader: [Object],
[js]       ResolveOptions: [Object],
[js]       ResolvePluginInstance: [Object],
[js]       RuleSetCondition: [Object],
[js]       RuleSetConditionAbsolute: [Object],
[js]       RuleSetConditionOrConditions: [Object],
[js]       RuleSetConditionOrConditionsAbsolute: [Object],
[js]       RuleSetConditions: [Object],
[js]       RuleSetConditionsAbsolute: [Object],
[js]       RuleSetLoader: [Object],
[js]       RuleSetLoaderOptions: [Object],
[js]       RuleSetRule: [Object],
[js]       RuleSetRules: [Object],
[js]       RuleSetUse: [Object],
[js]       RuleSetUseItem: [Object],
[js]       ScriptType: [Object],
[js]       SnapshotOptions: [Object],
[js]       SourceMapFilename: [Object],
[js]       SourcePrefix: [Object],
[js]       StatsOptions: [Object],
[js]       StatsValue: [Object],
[js]       StrictModuleExceptionHandling: [Object],
[js]       Target: [Object],
[js]       UmdNamedDefine: [Object],
[js]       UniqueName: [Object],
[js]       WasmLoading: [Object],
[js]       WasmLoadingType: [Object],
[js]       Watch: [Object],
[js]       WatchOptions: [Object],
[js]       WebassemblyModuleFilename: [Object],
[js]       WebpackOptionsNormalized: [Object],
[js]       WebpackPluginFunction: [Object],
[js]       WebpackPluginInstance: [Object]
[js]     },
[js]     description: 'Options object as provided by the user.',
[js]     type: 'object',
[js]     additionalProperties: false,
[js]     properties: {
[js]       amd: [Object],
[js]       bail: [Object],
[js]       cache: [Object],
[js]       context: [Object],
[js]       dependencies: [Object],
[js]       devServer: [Object],
[js]       devtool: [Object],
[js]       entry: [Object],
[js]       experiments: [Object],
error Command failed with exit code 1.
```

**Comment by evilebottnawi** [comment]
`namedModules` was removed in webpack@5

**Comment by achenwei-chwy** [comment]
@evilebottnawi plz close the ticket with a pause it will help devs to follow up 👍 
So the document thus need to be up to date, because I was looking at the doc for webpack 5.x namedModules is not removed.
<img width="293" alt="Screen Shot 2020-09-18 at 12 01 22 PM" src="https://user-images.githubusercontent.com/4201698/93619649-d7491600-f9a6-11ea-8e38-ba66f562fcf1.png">
<img width="783" alt="Screen Shot 2020-09-18 at 12 01 27 PM" src="https://user-images.githubusercontent.com/4201698/93619652-d7e1ac80-f9a6-11ea-913a-728f12358286.png">
