### ISSUE TITLE
Error: unknown option '--config'

### ISSUE THREAD

**Issue by karankumarshreds** [webpack/webpack-cli#2531]
<h1>Issue</h1>

I am getting an error message when I try to serve project using command: <br /> `start": "webpack serve --config config/webpack.dev.js`

> **Error**: 

```
$ npm run start

> marketing@1.0.0 start C:\Users\illum\Work\Study\Mircrofrontends\mfe\packages\marketing
> webpack serve --config config/webpack.dev.js

error: unknown option '--config'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! marketing@1.0.0 start: `webpack serve --config config/webpack.dev.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the marketing@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\illum\AppData\Roaming\npm-cache\_logs\2021-03-20T13_05_12_254Z-debug.log
```

# Dependencies

```
{
  "name": "marketing",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack serve --config config/webpack.dev.js",
    "build": "webpack --config config/webpack.prod.js"
  },
  "dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "babel-loader": "^8.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.0",
    "html-webpack-plugin": "^4.5.0",
    "style-loader": "^2.0.0",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.3.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.2.0"
  }
}
```

# Tried Resolution

When I upgrade the webpack-cli to **webpack-cli@4.3.0** I get :

> **Another Error**: 

```
[webpack-cli] TypeError: cli.isValidationError is not a function
    at Command.<anonymous> (C:\Users\illum\Work\Study\MircroFrontends\mfe\packages\marketing\node_modules\@webpack-cli\serve\lib\index.js:96:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\Users\illum\Work\Study\MircroFrontends\mfe\packages\marketing\node_modules\webpack-cli\lib\webpack-cli.js:708:13)
```

# Versions

**NPM** == 6.14.8

**NODE** == v14.15.0

**Comment by anshumanv** [comment]
Strange. Try upgrading cli to v4.5 and see if it stays

**Comment by alexander-akait** [comment]
Please remove `node_modules` and install deps again or just update your packages, you have the old version of `@webpack-cli/serve`

**Comment by karankumarshreds** [comment]
Okay, after alot of google-ing, this worked for me: 

I installed this cli serve package: 

```
npm i -D webpack-cli @webpack-cli/serve
```

Then I updated to **webpack-cli** to `"webpack-cli": "^4.5.0"` && **html-webpack-plugin** to `"html-webpack-plugin": "^5.1.0"`

I wonder why this was closed before it was even resolved.

**Comment by alexander-akait** [comment]
@karankumarshreds because nothing to fix on our side, how we should resolve this problem on our side, I give you advice how to solve it.
