### ISSUE TITLE
Installing the webpack-cli results in a RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SiriusNick** [webpack/webpack-cli#2582]
**Describe the bug**

I am trying to webpack my typescript library.
With only webpack installed the command runs just fine.
As soon as I install webpack-cli the same command results in an error.

**What is the current behavior?**

I get an error: `RangeError: Maximum call stack size exceeded`

**To Reproduce**

1. I assume you might need a projet with a large amount of ts files.
2. Install webpack with `npm install webpack --save-dev`
3. Run the `npx webpack` command
4. All works fine
5. Install webpack-cli with `npm install webpack-cli --save-dev`
6. Run the `npx webpack` command again
7. You get an error now

**Expected behavior**

Having the cli install shouldn't change the outcome of running webpack

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 3.68 GB / 15.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.54)
    Internet Explorer: 11.0.19041.1
  Packages:
    webpack: ^5.28.0 => 5.28.0
    webpack-cli: ^4.6.0 => 4.6.0
    webpack-node-externals: ^2.5.2 => 2.5.2
```

**Additional context**

My webpack.config.js
```
const path = require('path');
const nodeExternals = require('webpack-node-externals');

module.exports = {
	entry: './src/common.ts',
	module: {
		rules: [
			{
				test: /\.ts$/,
				use: [
					{
						loader: 'ts-loader',
						options: {
							configFile: "tsconfig.webpack.json"
						}
					}
				],
				exclude: [
					path.resolve(__dirname, '/node_modules')
				]
			}
		]
	},
	resolve: {
		extensions: [
			'.ts',
			'.js'
		]
	},
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'bundle.umd.js',
		libraryTarget: 'umd',
		globalObject: 'this'
	},
	node: {
		global: true
	},
	mode: 'none',
	devtool: 'source-map',
	target: 'node',
	externals: [
		nodeExternals(),
		'moment',
		'lodash',
		'url-parse'
	]
};
```

The error call stack:
```
ERROR in ./src/common.ts
Module parse failed: Maximum call stack size exceeded
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
RangeError: Maximum call stack size exceeded
    at new NullDependency (C:\Dev\MyTestProject\node_modules\webpack\lib\dependencies\NullDependency.js:1:1)
    at new CommonJsExportsDependency (C:\Dev\MyTestProject\node_modules\webpack\lib\dependencies\CommonJsExportsDependency.js:24:3)
    at handleAssignExport (C:\Dev\MyTestProject\node_modules\webpack\lib\dependencies\CommonJsExportsParserPlugin.js:164:16)
    at parser.hooks.assignMemberChain.for.tap (C:\Dev\MyTestProject\node_modules\webpack\lib\dependencies\CommonJsExportsParserPlugin.js:178:12)
    at Hook.eval [as call] (eval at create (C:\Dev\MyTestProject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at JavascriptParser.callHooksForInfoWithFallback (C:\Dev\MyTestProject\node_modules\webpack\lib\javascript\JavascriptParser.js:2935:24)
    at JavascriptParser.callHooksForInfo (C:\Dev\MyTestProject\node_modules\webpack\lib\javascript\JavascriptParser.js:2884:15)
    at JavascriptParser.walkAssignmentExpression (C:\Dev\MyTestProject\node_modules\webpack\lib\javascript\JavascriptParser.js:2476:11)
    at JavascriptParser.walkExpression (C:\Dev\MyTestProject\node_modules\webpack\lib\javascript\JavascriptParser.js:2193:10)
    at handleAssignExport (C:\Dev\MyTestProject\node_modules\webpack\lib\dependencies\CommonJsExportsParserPlugin.js:172:11)

webpack 5.28.0 compiled with 1 error in 18298 ms
```

**Comment by alexander-akait** [comment]
Sorry, not related to webpack-cli, please open an issue in webpack repo and **provide reproducible test repo** (otherwise an issue will be closed). Something wrong between `ts` and `webpack`, maybe you use new experimental syntax in ts and ts generate broken code
