### ISSUE TITLE
[migrate 4-5] ModuleNotFoundError: Module not found: Error: No parser registered for use

### ISSUE THREAD

**Issue by towry** [webpack/webpack-cli#2751]
**Describe the bug**

```
[webpack-cli] ModuleNotFoundError: Module not found: Error: No parser registered for use
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/Compilation.js:1762:28
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:732:13
    at eval (eval at create (/Users/towry/xxxcom/buck/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:274:22
    at eval (eval at create (/Users/towry/xxxcom/buck/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:550:15
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:573:8
    at done (/Users/towry/xxxcom/buck/node_modules/neo-async/async.js:2931:13)
    at /Users/towry/xxxcom/buck/node_modules/webpack/lib/NormalModuleFactory.js:979:14
    at finishResolved (/Users/towry/xxxcom/buck/node_modules/enhanced-resolve/lib/Resolver.js:278:11)
    at /Users/towry/xxxcom/buck/node_modules/enhanced-resolve/lib/Resolver.js:342:25
    at /Users/towry/xxxcom/buck/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/towry/xxxcom/buck/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/towry/xxxcom/buck/node_modules/enhanced-resolve/lib/Resolver.js:409:24
    at eval (eval at create (/Users/towry/xxxcom/buck/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
```

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**

**Additional context**

Current migrating webpack 4 project to webpack 5. All plugin upgrade to @latest.

What is the possible reason of this error?

**Comment by towry** [comment]
Invalid config in `module.rules`.
