### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ./webpack.config.ts

### ISSUE THREAD

**Issue by fregante** [webpack/webpack-cli#2916]
**Describe the bug**

Webpack is unable to read Webpack’s config file in TypeScript **if `type` is `module`.**  This is basically a duplicate of 

- https://github.com/webpack/webpack-cli/issues/2458

which reportedly has been fixed by

- https://github.com/webpack/webpack-cli/pull/2584

but it fails with the exact test config included in that PR.

**What is the current behavior?**

```
[webpack-cli] Failed to load './webpack.config.ts' config
[webpack-cli] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ./webpack.config.ts
    at new NodeError (node:internal/errors:329:5)
    at Loader.defaultGetFormat [as _getFormat] (node:internal/modules/esm/get_format:71:15)
    at Loader.getFormat (node:internal/modules/esm/loader:104:42)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:31)
    at async Loader.import (node:internal/modules/esm/loader:176:17)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfig (./node_modules/webpack-cli/lib/webpack-cli.js:1182:35)
    at async WebpackCLI.resolveConfig (./node_modules/webpack-cli/lib/webpack-cli.js:1290:38)
    at async WebpackCLI.createCompiler (./node_modules/webpack-cli/lib/webpack-cli.js:1670:22)
    at async WebpackCLI.buildCommand (./node_modules/webpack-cli/lib/webpack-cli.js:1785:20) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**To Reproduce**

```sh
echo '{"type": "module"}' > package.json
echo 'export default {}' > webpack.config.ts
echo 'console.log("hello world")' > index.js
echo '{"compilerOptions":{"module":"esnext", "allowSyntheticDefaultImports":true}}' > tsconfig.json
npm install webpack-cli webpack typescript ts-node
npx webpack-cli --entry ./index.js --mode production
```

If you drop `type:module` it reverts to the regular `Unexpected token 'export'` error.

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R)
  Binaries:
    Node: 15.14.0 - /usr/local/bin/node (also tried with node 16)
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Packages:
    webpack: ^5.51.1 => 5.51.1 
    webpack-cli: ^4.8.0 => 4.8.0 
  Global Packages:
    webpack-cli: 4.6.0
    webpack: 5.31.0
```

**Comment by fregante** [comment]
Repro and output (`webpack.log`) is also available at: https://github.com/fregante/webpack-sandbox/tree/main/ts-node-esm

**Comment by alexander-akait** [comment]
It was anwered here https://github.com/webpack/webpack-cli/issues/2458#issuecomment-811448600, we can't fix it on our side

**Comment by fregante** [comment]
> we can't fix it on our side

Can you catch the error and display a possible solution?

https://twitter.com/fregante/status/1407043890562179075

**Comment by alexander-akait** [comment]
> https://twitter.com/fregante/status/1407043890562179075

Maybe wrong link?

**Comment by fregante** [comment]
Correct link, I was showing what a good error looks like, which this isn't:

```
[webpack-cli] TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ./webpack.config.ts
```

**Comment by fregante** [comment]
As ESM packages become more popular, it's only time before more people encounter issues related to them. Google brought me to a StackOverflow answer that was "remove `type:module`" and the Webpack-specific search showed a mind-boggling _three_ results.

<img width="741" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/130602390-57c98e1d-8a5e-4d70-bb3e-aea6f55208ac.png">

**Comment by alexander-akait** [comment]
But we should the real error and why it happens, nothing to say more here, it should be fixed on `ts-node`

**Comment by alexander-akait** [comment]
Here right solution:
```
node --loader ts-node/esm node_modules/.bin/webpack-cli --entry ./index.js --mode production
```

**Comment by alexander-akait** [comment]
Only one thing valid here, we can add this to docs

**Comment by alexander-akait** [comment]
/cc @snitin315 @anshumanv We should improve our docs for ECMA modules and typescript ECMA modules output:
1. node --loader ts-node/esm node_modules/.bin/webpack-cli --entry ./index.js --mode production
2. NODE_OPTIONS="--loader ts-node/esm" npx webpack-cli --entry ./index.js --mode production (simplify)

**Comment by snitin315** [comment]
I will document it 👍🏻

**Comment by fregante** [comment]
I like the second one, without `npx`

**Comment by kasir-barati** [comment]
> Here right solution:
> 
> ```
> node --loader ts-node/esm node_modules/.bin/webpack-cli --entry ./index.js --mode production
> ```

Cannot be easily done in tools and build systems like Nx.

**Comment by alexander-akait** [comment]
@kasir-barati You can use https://nodejs.org/api/cli.html#node_optionsoptions

**Comment by xav-ie** [comment]
It seems that loaders are being deprecated or something. To get rid of the ugly output, you must use this asinine env:
```sh
NODE_OPTIONS="--import \"data:text/javascript,import { register } from 'node:module'; import { pathToFileURL } from 'node:url'; register('ts-node/esm', pathToFileURL('./'));\"" npx webpack
```
