### ISSUE TITLE
Unable to load '@webpack-cli/serve' command

### ISSUE THREAD

**Issue by jtoar** [webpack/webpack-cli#2990]
**Describe the bug**

RedwoodJS's dev server uses `webpack-dev-server` under the hood. It broke as soon as `@webpack-cli/serve` `v1.6` was released.

Redwood users start the dev server with `yarn rw dev`. It runs this command:

```
cd "${rwjsPaths.web.base}" && yarn cross-env NODE_ENV=development RWJS_WATCH_NODE_MODULES=${
  watchNodeModules ? '1' : ''
} webpack serve --config "${webpackDevConfig}" ${forward}`
```

Which resolves to something like:

```
$ /Users/dom/projects/redwood/_sandbox/my-redwood-app/node_modules/.bin/cross-env NODE_ENV=development 
RWJS_WATCH_NODE_MODULES= webpack serve --config /Users/dom/projects/redwood/_sandbox/my-redwood-app/node_modules/@redwoodjs/core/config/webpack.development.js
```

Our webpack development config can be found here; it's merged with our `webpack.common.js`, so I've included it as well:
- https://github.com/redwoodjs/redwood/blob/main/packages/core/config/webpack.development.js
- https://github.com/redwoodjs/redwood/blob/main/packages/core/config/webpack.common.js

**What is the current behavior?**

Currently, with the new release of `@webpack-cli/serve`, the dev server doesn't start up and throws:

```
web | [webpack-cli] Unable to load '@webpack-cli/serve' command
      [webpack-cli] TypeError: options.forEach is not a function
```

**To Reproduce**

1. create a `v0.37.2` redwood project using `yarn create redwood-app my-redwood-app`
2. run `yarn rw dev`
3. observe the error in the console

**Expected behavior**

The dev server starts up successfully on `localhost:8910`.

**Screenshots**

The dev server broken:
![image](https://user-images.githubusercontent.com/32992335/136315168-6e6ef57b-b529-4b35-a31d-317d127e4b41.png)
The dev server:
![image](https://user-images.githubusercontent.com/32992335/136315343-543fdeda-a733-418d-a1d5-450035a182d6.png)

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**

```
  System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 127.65 MB / 8.00 GB
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 14.0.2
  Monorepos:
    Yarn Workspaces: 1.22.10
```

**Additional context**

- Here's the bug report in redwoodjs/redwood: https://github.com/redwoodjs/redwood/issues/3522
- Here's our temporary fix: https://github.com/redwoodjs/redwood/pull/3524

**Comment by clandsky** [comment]
Hi, i get a similar issue when i run browserDevelopmentRun target via gradle, which calls @webpack-cli/serve. I was tinkering around with KotlinJs. 
Seems, that 1.6.0 broke the build. Until then, everything worked fine for me. 

`[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\lib\webpack-cli.js:173:21)
    at ServeCommand.apply (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\node_modules\@webpack-cli\serve\lib\index.js:41:19)
    at loadCommandByName (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\lib\webpack-cli.js:907:35)
    at async Command.<anonymous> (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1462:17)
    at async Promise.all (index 0)
    at async WebpackCLI.run (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\lib\webpack-cli.js:1500:9)
    at async runCLI (D:\Workspace\clsky.de\build\js\node_modules\webpack-cli\lib\bootstrap.js:11:9)
`

**Comment by alexander-akait** [comment]
Anyway feel free to feedback

**Comment by Artur-** [comment]
Surely you cannot be saying that it is OK that 4.8.0 stops working because 4.9.0 is available?

**Comment by alexander-akait** [comment]
Sorry for delay, will have time tomorrow, top on my TODO

**Comment by Alexstoppel** [comment]
Any update on this, especially for V.5.58?

**Comment by damdeez** [comment]
☝️ same here

**Comment by hackpros** [comment]
update  your package.json
    "webpack-cli": "4.9.0",
    "webpack-dev-server": "^4.4.0",

**Comment by jiyosub** [comment]
> update your package.json "webpack-cli": "4.9.0", "webpack-dev-server": "^4.4.0",

No production canister_ids.json found. Continuing with local
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'watchContentBase'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, static?, watchFiles?, webSocketServer? }

**Comment by jiyosub** [comment]
My fix:

**package.json** 
```
"webpack-cli": "4.9.1",
"webpack-dev-server": "^4.5.0"
```

**webpack.config.js** - modify devServer settings to:
```
// proxy /api to port 8000 during development
  devServer: {
    proxy: {
      "/api": {
        target: "http://localhost:8000",
        changeOrigin: true,
        pathRewrite: {
          "^/api": "/api",
        },
      },
    },
    hot: true,
    static: path.resolve(__dirname, "./src/hello_assets")  },
};

```

**Comment by DrThouraya** [comment]
> My fix:
> 
> **package.json**
> 
> ```
> "webpack-cli": "4.9.1",
> "webpack-dev-server": "^4.5.0"
> ```
> 
> **webpack.config.js** - modify devServer settings to:
> 
> ```
> // proxy /api to port 8000 during development
>   devServer: {
>     proxy: {
>       "/api": {
>        target: "http://127.0.0.1:8000",
>         changeOrigin: true,
>         secure: false,
>         pathRewrite: {
>           "^/api": "/api",
>         },
>       },
>     },
>     hot: true,
>     static: path.resolve(__dirname, "./src/hello_assets")  },
> };
> ```an

**Comment by DrThouraya** [comment]
> My fix:
> 
> **package.json**
> 
> ```
> "webpack-cli": "4.9.1",
> "webpack-dev-server": "^4.5.0"
> ```
> 
> **webpack.config.js** - modify devServer settings to:
> 
> ```
> // proxy /api to port 8000 during development
>   devServer: {
>     proxy: {
>       "/api": {
>        target: "http://127.0.0.1:8000",
>         changeOrigin: true,
>         secure: false,
>         pathRewrite: {
>           "^/api": "/api",
>         },
>       },
>     },
>     hot: true,
>     static: path.resolve(__dirname, "./src/hello_assets")  },
> };
> ```

Hi! any help please?

I have two package.json under my web app repository [https://github.com/DrThouraya/regards-frontend/tree/master/webapp](url).
The first one is under the "webapp" directory and the second one is under the web pack-config-front..
so, which one to change? 
FYI: I have installed npm -v=5.7.1 and node -v=8.10.0
and I got an error message when  trying to run this command:

`npm run start:withpreprod`
![runstart](https://user-images.githubusercontent.com/21196992/147471274-e3a5f76e-b735-4394-accc-c40d1c61b176.png)

I got also an error message when typing `or 

`npm run build:production
npm run build:plugins`
`

Thanks in advance.

**Comment by alexander-akait** [comment]
Run `npm ls webpack-cli` and `npm ls webpack-dev-server`

**Comment by DrThouraya** [comment]
> npm ls webpack-cli
Hi @alexander-akait , I got 
for `npm ls webpack-cli`, I got  --> ERR! invalid: webpack-cli@4.6.0 
and for `npm ls webpack-dev-server `, no error message --> webpack-dev-server@3.11.3

**Comment by alexander-akait** [comment]
Update webpack-cli to the latest stable version

**Comment by DrThouraya** [comment]
> Update webpack-cli to the latest stable version

done! but I still getting the same error message when typing `npm run start:withpreprod..
![runstart](https://user-images.githubusercontent.com/21196992/147473761-6c9ebadc-31a3-439e-bb74-b53a2db9795d.png)
`

**Comment by DrThouraya** [comment]
> Update webpack-cli to the latest stable version

done! but I still getting the same error  when typing `npm run start:withpreprod ` ..

![runstart](https://user-images.githubusercontent.com/21196992/147473865-f1ebe668-305b-4f24-a79d-02f49d1c6e91.png)

**Comment by alexander-akait** [comment]
What is `Node.js` version?  Looks your version is not supported that https://github.com/webpack/webpack/blob/main/lib/cli.js#L67

**Comment by DrThouraya** [comment]
> What is `Node.js` version? Looks your version is not supported that https://github.com/webpack/webpack/blob/main/lib/cli.js#L67

my node version is 8.10.0
The manual that I am using asked me to install nodejs 8.10 and npm 5.7.1 to can test the frontend repository locally..

**Comment by alexander-akait** [comment]
I am afraid your manual is outdated, minimum supported `Node.js` version is `10.13` https://github.com/webpack/webpack/blob/main/package.json#L113, but I strongly recommend to use the latest LTS, i.e. `16.13.1`

**Comment by DrThouraya** [comment]
if you look in their file "package.json", they indicate [https://github.com/DrThouraya/regards-frontend/blob/master/webapp/package.json](url) 

`"engines": {
    "node": ">=6.11.2",
    "npm": ">=3.10.10"`

**Comment by alexander-akait** [comment]
Versions are wrong, you can't use `6.11.2` node with webpack v5

**Comment by Efrony** [comment]
it helped me 
"webpack-cli": "^4.9.1",

**Comment by DrThouraya** [comment]
Hi and thank you for your answer,  and what about node and npm versions  and webpack-dev-server? Thank you!

**Comment by Efrony** [comment]
> Hi and thank you for your answer, and what about node and npm versions and webpack-dev-server? Thank you!
    "webpack": "5.28.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "3.11.2"

npm --version
6.14.13

node --version
v14.17.3

**Comment by andriihuchko** [comment]
npm install --save-dev webpack-cli working for me
