### ISSUE TITLE
HookWebpackError: Not supported

### ISSUE THREAD

**Issue by darmentrout** [webpack/webpack-cli#3029]
**Describe the bug**

Attempting the build process results in an error that is vague: `[webpack-cli] HookWebpackError: Not supported`

**What is the current behavior?**

```
[user@host project]$ yarn build
yarn run v1.22.10
$ webpack --env env=production
[webpack-cli] HookWebpackError: Not supported
    at makeWebpackError (/home/user/project/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at hooks.processAssets.callAsync.err (/home/user/project/node_modules/webpack/lib/Compilation.js:3055:12)
    at eval (eval at create (/home/user/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:74:1)
    at err (/home/user/project/node_modules/webpack/lib/Compilation.js:508:26)
    at compilation.hooks.processAssets.tapAsync (/home/user/project/node_modules/copy-webpack-plugin/dist/index.js:485:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-- inner error --
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/home/user/project/node_modules/copy-webpack-plugin/dist/index.js:481:13)
    at fn (/home/user/project/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/home/user/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:72:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/user/project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/user/project/node_modules/webpack/lib/Compilation.js:3052:34)
    at createChunkAssets.err (/home/user/project/node_modules/webpack/lib/Compilation.js:3100:10)
    at symbolIterator (/home/user/project/node_modules/neo-async/async.js:3485:9)
    at done (/home/user/project/node_modules/neo-async/async.js:3527:9)
    at /home/user/project/node_modules/neo-async/async.js:2830:7
    at done (/home/user/project/node_modules/neo-async/async.js:2865:11)
caused by plugins in Compilation.hooks.processAssets
Error: Not supported
    at compilation.hooks.processAssets.tapAsync (/home/user/project/node_modules/copy-webpack-plugin/dist/index.js:481:13)
    at fn (/home/user/project/node_modules/webpack/lib/Compilation.js:507:9)
    at Hook.eval [as callAsync] (eval at create (/home/user/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:72:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/user/project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/user/project/node_modules/webpack/lib/Compilation.js:3052:34)
    at createChunkAssets.err (/home/user/project/node_modules/webpack/lib/Compilation.js:3100:10)
    at symbolIterator (/home/user/project/node_modules/neo-async/async.js:3485:9)
    at done (/home/user/project/node_modules/neo-async/async.js:3527:9)
    at /home/user/project/node_modules/neo-async/async.js:2830:7
    at done (/home/user/project/node_modules/neo-async/async.js:2865:11)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

run the yarn build script (`webpack --env env=production`)

**Expected behavior**

An error-free build or more descriptive errors

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: Linux 4.18 Red Hat Enterprise Linux 8.5 (Ootpa)
  Binaries:
    Node: 10.24.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/project/node_modules/.bin/npm
  Browsers:
    Firefox: support!
Mozilla Firefox 91.3.0esr
  Packages:
    babel-loader: ^8.2.3 => 8.2.3
    clean-webpack-plugin: ^4.0.0 => 4.0.0
    copy-webpack-plugin: ^10.0.0 => 10.0.0
    css-loader: ^6.5.1 => 6.5.1
    css-minimizer-webpack-plugin: ^3.1.4 => 3.1.4
    file-loader: ^6.2.0 => 6.2.0
    html-webpack-plugin: ^5.5.0 => 5.5.0
    optimize-css-assets-webpack-plugin: ^6.0.1 => 6.0.1
    sass-loader: ^12.3.0 => 12.3.0
    style-loader: ^3.3.1 => 3.3.1
    svg-url-loader: ^7.1.1 => 7.1.1
    webpack: ^5.64.1 => 5.64.1
    webpack-cli: ^4.9.1 => 4.9.1
    webpack-dev-server: ^4.5.0 => 4.5.0
    webpack-merge: ^5.8.0 => 5.8.0
    yaml-loader: ^0.6.0 => 0.6.0
```

**Additional context**
```
[user@host project]$ yarn webpack -v
yarn run v1.22.10
$ /home/user/project/node_modules/.bin/webpack -v
webpack: 5.64.1
webpack-cli: 4.9.1
webpack-dev-server 4.5.0
Done in 0.31s.

[user@host project]$ yarn webpack -v
yarn run v1.22.10
$ /home/user/project/node_modules/.bin/webpack -v
webpack: 5.64.1
webpack-cli: 4.9.1
webpack-dev-server 4.5.0
Done in 0.31s.
```

**Comment by alexander-akait** [comment]
Only `Node.js` v12.20 supported https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/package.json#L16

**Comment by iamgabrielsoft** [comment]
I had the same isuse running npm run build in a Nextjs project
