### ISSUE TITLE
TypeError: options.forEach is not a function

### ISSUE THREAD

**Issue by JiakaiYang** [webpack/webpack-cli#3054]
**Describe the bug**

TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (E:\webpackTest\node_modules\webpack-cli\lib\webpack-cli.js:108:21)
    at ServeCommand.apply (E:\webpackTest\node_modules\@webpack-cli\serve\lib\index.js:41:19)
    at loadCommandByName (E:\webpackTest\node_modules\webpack-cli\lib\webpack-cli.js:626:35)
    at Command.<anonymous> (E:\webpackTest\node_modules\webpack-cli\lib\webpack-cli.js:1091:23)
    at Command.listener [as _actionHandler] (E:\webpackTest\node_modules\webpack-cli\node_modules\commander\index.js:922:31)
    at Command._parseCommand (E:\webpackTest\node_modules\webpack-cli\node_modules\commander\index.js:1503:14)
    at Command.parse (E:\webpackTest\node_modules\webpack-cli\node_modules\commander\index.js:1292:10)
    at Command.parseAsync (E:\webpackTest\node_modules\webpack-cli\node_modules\commander\index.js:1318:10)
    at WebpackCLI.run (E:\webpackTest\node_modules\webpack-cli\lib\webpack-cli.js:1123:28)
    at runCLI (E:\webpackTest\node_modules\webpack-cli\lib\bootstrap.js:11:19)

![image](https://user-images.githubusercontent.com/79317176/145142387-146c46a4-68eb-4b8c-b96e-c6923a34500a.png)

I get an error when I run "npx webpack serve or npx webpack-dev-server"
I changed 2 versions, 3.5.0 and 4.5.0

**Comment by snitin315** [comment]
Please update `webpack-cli` to the latest version `4.9.1` and follow the issue template.
