### ISSUE TITLE
Import error after updating to v5.1.2

### ISSUE THREAD

**Issue by vpmedia** [webpack/webpack-cli#3833]
**Describe the bug**

Up until now I've used the webpack.config.babel.js naming convention to use ES6 in my webpack configuration file.
After updating to v5.1.2 I'm getting the following import error:

```
[webpack-cli] Failed to load '/..../webpack.config.babel.js' config
[webpack-cli] /..../webpack.config.babel.js:9
import { resolve } from 'path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1175:20)
    at Module._compile (node:internal/modules/cjs/loader:1219:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at WebpackCLI.tryRequireThenImport (/..../node_modules/webpack-cli/lib/webpack-cli.js:223:30)
    at loadConfigByPath (/..../node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
```

Any tips about migrating? I've not found any code migration related comment regarding this in the release notes. Also if there were some braking changes I would expect to bump the major version.

Thank you!

**Comment by fbarbare** [comment]
@alexander-akait I updated to v5.1.4 and I am getting this same issue when my babel config imports another file that uses the `import` statement. Is there something I would need to do to resolve this?

**Comment by nyngwang** [comment]
@alexander-akait I have the same issue when writing webpack.config.js in ESM. I think this issue should be reopened.

```
✘:2 ~/GitHub/Frontend % npm run dev development                                                                                                                            13:41:35

> frontend@0.0.1 dev
> webpack server --mode development

[webpack-cli] Failed to load '/Users/ningwang/GitHub/Frontend/webpack.config.js' config
[webpack-cli] /Users/ningwang/GitHub/Frontend/webpack.config.js:1
import path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at WebpackCLI.tryRequireThenImport (/Users/ningwang/GitHub/Frontend/node_modules/webpack-cli/lib/webpack-cli.js:223:30)
    at loadConfigByPath (/Users/ningwang/GitHub/Frontend/node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
```

**Comment by alexander-akait** [comment]
@fbarbare Can you create a reproducible test repo?

**Comment by nyngwang** [comment]
@fbarbare Try renaming everything `webpack.config.js` import, directly/indirectly, with `.mjs` extension.
