### ISSUE TITLE
Cannot read properties of undefined (reading 'getArguments')

### ISSUE THREAD

**Issue by titanve** [webpack/webpack-cli#3911]
**Describe the bug**
Getting this error:
```
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'getArguments')
    at WebpackCLI.getBuiltInOptions (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:831:77)
    at makeCommand.options.entry (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:939:33)
    at async WebpackCLI.makeCommand (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:443:31)
    at async loadCommandByName (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:937:17)
    at async Command.<anonymous> (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:1336:17)
    at async Command.parseAsync (/Users/rafa.mora/Sites/sender_id/node_modules/commander/lib/command.js:935:5)
    at async WebpackCLI.run (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/webpack-cli.js:1360:9)
    at async runCLI (/Users/rafa.mora/Sites/sender_id/node_modules/webpack-cli/lib/bootstrap.js:9:9)
```

when running: 
```
bin/rails assets:precompile
```

**What is the current behavior?**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please paste the results of `npx webpack-cli info` here, and mention other relevant information**
```
npx webpack-cli info                                                                                                                                    1 ✘  4s  ruby-3.0.5   14:58:37

  System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.45 GB / 32.00 GB
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/Sites/sender_id/node_modules/.bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.51
    Firefox: 112.0.2
    Safari: 16.6
  Packages:
    eslint-import-resolver-webpack: ^0.13.4 => 0.13.4
    webpack-cli: ^5.1.4 => 5.1.4
    webpack-dev-server: ^4 => 4.15.1
```
**Additional context**
```
"webpack-cli": "^5.1.4",
"webpack-dev-server": "^4",
"@rails/webpacker": "5.4.4"
```

**Comment by evenstensberg** [comment]
Could you create a repo with reproduction steps?

**Comment by dylearn** [comment]
waiting an answer....

**Comment by snitin315** [comment]
Ideally, you would get this error when using an incompatible version of webpack with webpack-cli, for reference:
- webpack-cli v4 supports webpack v4 and webpack v5
- webpack-cli v5 supports only webpack v5

`getArguments` was added in webpack v5 only.

https://github.com/webpack/webpack-cli/blob/d40d4a67db8bf91c960d9dd3d0fbe5dbbf656ba3/packages/webpack-cli/src/webpack-cli.ts#L1071

**Comment by evenstensberg** [comment]
@snitin315 It’s a ruby project so we’ll need to see the deps

**Comment by evenstensberg** [comment]
@titanve could you give us a reproduction repository?

**Comment by alexander-akait** [comment]
Please run `npm ls webpack` and you will see you are still using webpack@4, please open an issue in `@rails/webpacker`, feel free to feedback

**Comment by titanve** [comment]
@evenstensberg 

This is a private repo. What should I do in order to fix this issue? Thanks.

**Comment by titanve** [comment]
running `npm ls webpack` threw these errors:
```
npm ls webpack                                                                                                                                                                            ✔  20s  3.0.5   10:48:56
npm ERR! code ELSPROBLEMS
npm ERR! invalid: webpack@4.46.0 /Users/rafael.mora/Sites/sender_id/node_modules/webpack
sender_id@0.1.0 /Users/rafael.mora/Sites/sender_id
├─┬ @rails/webpacker@5.4.4
│ ├─┬ babel-loader@8.2.3
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ compression-webpack-plugin@4.0.1
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ css-loader@3.6.0
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ mini-css-extract-plugin@0.9.0
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ optimize-css-assets-webpack-plugin@5.0.8
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ sass-loader@10.1.1
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ style-loader@1.3.0
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ terser-webpack-plugin@4.2.3
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ webpack-assets-manifest@3.1.1
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ ├─┬ webpack-cli@3.3.12
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
│ └─┬ webpack@4.46.0 invalid: "5.x.x" from node_modules/webpack-cli
│   └─┬ terser-webpack-plugin@1.4.5
│     └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli, "5.x.x" from node_modules/@webpack-cli/configtest, "5.x.x" from node_modules/@webpack-cli/info, "5.x.x" from node_modules/@webpack-cli/serve
├─┬ eslint-import-resolver-webpack@0.13.8
│ └── webpack@4.46.0 deduped
├─┬ webpack-cli@5.1.4
│ ├─┬ @webpack-cli/configtest@2.1.1
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli, "5.x.x" from node_modules/@webpack-cli/configtest
│ ├─┬ @webpack-cli/info@2.0.2
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli, "5.x.x" from node_modules/@webpack-cli/configtest, "5.x.x" from node_modules/@webpack-cli/info
│ ├─┬ @webpack-cli/serve@2.0.5
│ │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli, "5.x.x" from node_modules/@webpack-cli/configtest, "5.x.x" from node_modules/@webpack-cli/info, "5.x.x" from node_modules/@webpack-cli/serve
│ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
└─┬ webpack-dev-server@4.15.1
  ├─┬ webpack-dev-middleware@5.3.1
  │ └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli, "5.x.x" from node_modules/@webpack-cli/configtest, "5.x.x" from node_modules/@webpack-cli/info, "5.x.x" from node_modules/@webpack-cli/serve
  └── webpack@4.46.0 deduped invalid: "5.x.x" from node_modules/webpack-cli
```

**Comment by alexander-akait** [comment]
As you can see, you have the new version of `webpack-cli`, but use the old version of `webpack` (i.e. 4), please use the old version of `wepack-cli`

**Comment by alexander-akait** [comment]
@titanve This is good tool https://github.com/shakacode/shakapacker, migration should not be hard

**Comment by titanve** [comment]
@alexander-akait Ok I'm gonna try it!

Thanks!
