### ISSUE TITLE
Webpack wants to install webpack-cli

### ISSUE THREAD

**Issue by alistair-hmh** [webpack/webpack-cli#430]
## Versions

- Webpack@4.6.0
- Node@v10.0.0
- NPM@5.6.0

## Request Type

BUG! 🐞 

## Bhavior

`Webpack` asks me to install `webpack-cli`; but `webpack-cli` already exists in the project

## Steps to Reproduce

```shell
brew install node
npm install -g webpack
```

Create the following `package.json`:

```json
{
  "dependencies": {
    "@types/react": "^16.3.13",
    "@types/react-dom": "^16.0.5",
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  },
  "devDependencies": {
    "awesome-typescript-loader": "^5.0.0",
    "source-map-loader": "^0.2.3",
    "typescript": "^2.8.3",
    "webpack": "^4.6.0",
    "webpack-cli": "^2.1.2"
  }
}
```

Install things...

```shell
npm install
````

Try running webpack:

```shell
webpack

# The CLI moved into a separate package: webpack-cli
# Would you like to install webpack-cli? (That will run npm install -D webpack-cli) (yes/NO)
```

Even if I choose "yes", and install `webpack-cli` (again), the following happens:

```
# The CLI moved into a separate package: webpack-cli
# Would you like to install webpack-cli? (That will run npm install -D webpack-cli) (yes/NO)yes
# npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
# npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
# + webpack-cli@2.1.2
# removed 1 package and updated 1 package in 19.266s
# { Error: Cannot find module 'webpack-cli'
#     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
#     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
#     at Module.require (internal/modules/cjs/loader.js:626:17)
#     at require (internal/modules/cjs/helpers.js:20:18)
#     at runCommand.then.result (/usr/local/lib/node_modules/webpack/bin/webpack.js:62:14)
#     at process._tickCallback (internal/process/next_tick.js:178:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by ematipico** [comment]
It seems that your environment is picking up the webpack installed globally. Could you try to NOT install globally webpack and try again please?

**Comment by alistair-hmh** [comment]
Is Webpack not intended to be used globally any more?

(All the examples I've been looking at online are using Webpack globally.)

**Comment by ev1stensberg** [comment]
Both global and local, we're gonna go for only global soon

**Comment by ematipico** [comment]
Only global? What if some user wanted/needed/forced to have it local? We have to remember that there are also closed environment where it's not possible to install global packages.

**Comment by TitanRtx** [comment]
aha! how ** is this problem, i can't use it , indeed, the last time i  used webpack is last year ,  this days , i suddenly have some idea and need webpack helping me mange my js app , however , i even can't install it just because it said that  i need install webpackcli first , but i have installed it ,  both global and local , please fix this problem , i need it .

**Comment by evenstensberg** [comment]
Try installing them both locally
