### ISSUE TITLE
--info-verbosity causes error/failure

### ISSUE THREAD

**Issue by domehead100** [webpack/webpack-cli#459]
**Describe the bug**

Launched webpack-cli --info-verbosity verbose.  Got an error/exit at: 
```javascript
/node_modules/webpack-cli/bin/webpack.js:460
  compiler.hooks.beforeCompile.tap("WebpackInfo", compilation => {
```

due to the beforeCompile hook being undefined.

**What is the current behavior?**

Errors if --info-verbosity is used.

**To Reproduce**
1. Launch webpack-cli with flag --info-verbosity verbose.
2. See webpack exit with error at:
```javascript
/node_modules/webpack-cli/bin/webpack.js:460
  compiler.hooks.beforeCompile.tap("WebpackInfo", compilation => {
```
**Expected behavior**
Expect info-verbosity switch with verbose to cause webpack-cli to display messages before and after compilation that can be used with vscode problem matches to convert errors to "problems" in the UI.

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information*

 System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.9.1
    Yarn: 1.5.1
    npm: 5.6.0
  Browsers: {}
  npmPackages:
    case-sensitive-paths-webpack-plugin:
      wanted: ^2.1.2
      installed: 2.1.2
    copy-webpack-plugin:
      wanted: ^4.5.1
      installed: 4.5.1
    eslint-import-resolver-webpack:
      wanted: ^0.10.0
      installed: 0.10.0
    extract-text-webpack-plugin:
      wanted: ^4.0.0-beta.0
      installed: 4.0.0-beta.0
    fork-ts-checker-webpack-plugin:
      wanted: ^0.4.1
      installed: 0.4.1
    only-if-changed-webpack-plugin:
      wanted: 0.0.1
      installed: 0.0.1
    optimize-css-assets-webpack-plugin:
      wanted: ^4.0.1
      installed: 4.0.1
    uglifyjs-webpack-plugin:
      wanted: ^1.2.5
      installed: 1.2.5
    webpack:
      wanted: ^4.8.3
      installed: 4.8.3
    webpack-bundle-analyzer:
      wanted: ^2.13.0
      installed: 2.13.0
    webpack-cleanup-plugin:
      wanted: github:domehead100/webpack-cleanup-plugin
      installed: 0.5.2
    webpack-cli:
      wanted: ^2.1.3
      installed: 2.1.3
    webpack-dashboard:
      wanted: ^1.1.1
      installed: 1.1.1
    webpack-manifest-plugin:
      wanted: ^2.0.2
      installed: 2.0.3
    webpack-merge:
      wanted: ^4.1.2
      installed: 4.1.2
    webpack-node-externals:
      wanted: ^1.7.2
      installed: 1.7.2
    webpack-runner:
      wanted: ^3.0.1
      installed: 3.0.1
    webpack-shell-plugin:
      wanted: ^0.5.0
      installed: 0.5.0
    webpack-visualizer-plugin:
      wanted: ^0.1.11
      installed: 0.1.11

**Additional context**

**Comment by ev1stensberg** [comment]
Yields fine here:

<img width="563" alt="skjermbilde 2018-05-23 kl 18 56 26" src="https://user-images.githubusercontent.com/16735925/40439366-05a45ac0-5ebb-11e8-8568-f0a7881b03ef.png">


Could you give me a repro, i.e access to your source code? Might be hard to debug.

**Comment by ev1stensberg** [comment]
Friendly ping :)

**Comment by jpoppe** [comment]
This one gave me a headache, took me a while to find issue but for me this happens when there are multiple targets exported, also when _module.exports_ is an array with one target.

This works with _--info-verbosity:_
```javascript
module.exports = webpackConfiguration
```

This does not work with _--info-verbosity_:
```javascript
module.exports = [webpackConfiguration]
module.exports = [webpackConfiguration1, webpackConfiguration2]
```

**Comment by ev1stensberg** [comment]
I don't think exporting an array of modules is encouraged, one file with a config is considered better

**Comment by jpoppe** [comment]
@ev1stensberg When you are building an Electron application with 2 targets then this is a pretty useful supported feature ;)

**Comment by diegocl02** [comment]
I got the same problem here, @jpoppe did you use any workaround for it? I want to use the --info-verbosity flag and at the same time I want to have multiple targets exported in my conf file.

**Comment by jpoppe** [comment]
@diegocl02, no I did not find a work around, I found this issue when I tried to debug another issue I had with Webpack, so I just enabled only one target for debugging so I could use the _--info-verbosity_ flag. But it did not show more then the --verbose flag in the end so I did not spent more time on it.

**Comment by ev1stensberg** [comment]
Could you formulate the error precisely? i.e: `info-verbosity` doesn't work when exporting multiple configurations.

**Comment by jpoppe** [comment]
@ev1stensberg: exactly that, I must add that I have only tested with exporting multiple configurations with different targets, **electron-main** and  **electron-renderer** in my case.

**Comment by ev1stensberg** [comment]
By chance, do you merge configurations at any point?

**Comment by ev1stensberg** [comment]
Hi @domehead100 wow, that's quite extensive, you're smart! 

My hypothesis is that `webpack-merge` doesn't merge the two configurations correctly. If you can console log the exported configurations before exporting them, filter out confidencial content and log them here, that would be great.

**Comment by domehead100** [comment]
Ha.  If I was smart, our setup would be simple :).  "Any fool can make something complicated.”  Thanks though, even if you were ribbing me.

Anyway, here's culled output from our dev build without --info-verbosity in the command line (so that the build will actually run).  Search for "step1", "step2", "step3" to see the console.log() output of the configs.  In reality, these came out in reverse in the actual console output (step3, step2, step1) so I manually edited the output to put them in order of occurrence.   I guess the log statements were run as the stack unwound. 

In our React config(s), we use the functional form of module.exports, so I put console.log() statements at the end before the config was being returned (and again, they came out in reverse order in the output):

```javascript
module.exports = (env, opts) => {
  ...
  console.log(<the config>);
  return <the config>;
}
```
The only thing that I see that is kind of interesting is that the plugins array in what was logged as "step1" shows mostly entries of type [Object], whereas in the child/chained configs, the plugins arrays show actual plugin names.  Again, keep in mind that "step1" actually was logged last in the real console output.  (Maybe I should have just left the output alone?).

It now occurs to me that using merge on the plugins array is probably a bad idea, since a merge would have a hard time with an array.  I'll try not using merge and just concat plugins from dev/prod and see if I get the error.

```typescript
building React vendor bundle (sync)
=> .\React\webpack.config.vendor.js
env development
Time: 3646ms
React vendor bundle built or unchanged
...
step1: parallel configs exported from root config 
    // file: ./webpack.config.js
    // const rv = [
    //     env === "development" 
    //         ? require("./webpack.config.dev.js") 
    //         : require("./webpack.config.prod.js"),
    //     require("./React/webpack.config.js")(env, opts),
    // ];
    // console.log("step1: parallel configs exported from root config", rv);
    // return rv;
[ 
  { 
    name: 'jQuery',
    mode: 'development',
    devtool: '#cheap-module-eval-source-map',
    stats:
     { all: false,
       colors: true,
       errors: true,
       errorDetails: false,
       warnings: true,
       timings: true,
       chunks: false,
       chunkOrigins: false,
       entrypoints: true,
       depth: false,
       warningsFilter: [Array] },
    entry:
     { // about 20 separate bundles are build on the jQuery side },
    externals: { angular: 'angular', jquery: '$' },
    module: { rules: [Array] },
    node: { fs: 'empty', net: 'empty', tls: 'empty' },
    output:
     { filename: '[name].js',
       path: .\\dist\\main',
       pathinfo: true },
    plugins: [ CheckerPlugin {}, [Object], [Object] ],
    resolve: { extensions: [Array] } 
  },
  { 
    name: 'React',
    resolve: { extensions: [Array], modules: [Array], alias: [Object] },
    node: { fs: 'empty', net: 'empty', tls: 'empty', vertx: 'empty' },
    stats:
     { all: false,
       colors: true,
       errors: true,
       errorDetails: false,
       warnings: true,
       timings: true,
       chunks: true,
       chunkOrigins: false,
       entrypoints: true,
       depth: false,
       reasons: false,
       source: false,
       moduleTrace: false,
       warningsFilter: [Array] },
    entry:
     { app: [Array],
       tabularReports: [Array],
       codingPage: [Array],
       emCalculator: [Array],
       inbox: [Array],
       auditing: [Array] },
    output:
     { path: .\\dist\\react',
       publicPath: 'React/',
       filename: '[name].js',
       chunkFilename: '[name].js' },
    module: { rules: [Array] },
    plugins:
     [ [Object],
       NoEmitOnErrorsPlugin {},
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    mode: 'development',
    devtool: '#cheap-module-eval-source-map',
    watch: true } 
]

building jQuery bundles (async)
=> .\webpack.config.js
env development

...

building React bundles (async)
=> .\React\webpack.config.js
env development
=> .\React\webpack.config.dev.js
env development

...

step2: React root config returns prod or dev config:
{
  name: 'React',
  resolve:
   { extensions: [ '.ts', '.tsx', '.js', '.jsx', 'web.jsx', 'web.js', '.json' ],
     modules: [ 'src', 'node_modules' ],
  node: { fs: 'empty', net: 'empty', tls: 'empty', vertx: 'empty' },
  stats:
   { all: false,
     colors: true,
     errors: true,
     errorDetails: false,
     warnings: true,
     timings: true,
     chunks: true,
     chunkOrigins: false,
     entrypoints: true,
     depth: false,
     reasons: false,
     source: false,
     moduleTrace: false,
     warningsFilter:
      [ /WARNING in \./g,
        /export 'IValidation' was not found in '_types\/IValidation'/g,
        /export 'FormField' was not found in '\.\/form-model'/g,
        'dummy string' ] },
  entry:
   { app:
      [ .\\React\\src\\_entry\\app' ],
     bundle1:
      [ .\\React\\src\\_entry\\bundle1' ],
     bundle2:
      [ .\\React\\src\\_entry\\bundle2' ],
     bundle3:
      [ .\\React\\src\\_entry\\bundle3' ],
     bundle4:
      [ .\\React\\src\\_entry\\bundle4' ],
     bundle5:
      [ .\\React\\src\\_entry\\bundle5' ] },
  output:
   { path: .\\dist\\react',
     publicPath: 'React/',
     filename: '[name].js',
     chunkFilename: '[name].js' },
  module: { rules: [ [Object], [Object], [Object], [Object] ] },
  plugins:
   [ CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     NoEmitOnErrorsPlugin {},
     WebpackCleanupPlugin { options: [Object] },
     WatchIgnorePlugin { paths: [Array] },
     ForkTsCheckerWebpackPlugin {
       options: {},
       tsconfig: './tsconfig.json',
       tslint: undefined,
       watch: [],
       ignoreDiagnostics: [],
       ignoreLints: [],
       logger: [Object],
       silent: false,
       async: true,
       checkSyntacticErrors: false,
       workersNumber: 1,
       memoryLimit: 2048,
       useColors: true,
       colors: [Object],
       formatter: [Function: defaultFormatter],
       tsconfigPath: undefined,
       tslintPath: undefined,
       watchPaths: [],
       compiler: undefined,
       started: undefined,
       elapsed: undefined,
       cancellationToken: undefined,
       isWatching: false,
       checkDone: false,
       compilationDone: false,
       diagnostics: [],
       lints: [],
       emitCallback: [Function: noopEmitCallback],
       doneCallback: [Function: doneCallback],
       typescriptVersion: '2.8.3',
       tslintVersion: undefined,
       vue: false },
     MiniCssExtractPlugin { options: [Object] },
     DllReferencePlugin { options: [Object] },
     IgnorePlugin {
       resourceRegExp: /vertx/,
       contextRegExp: undefined,
       checkIgnore: [Function: bound checkIgnore] },
     DefinePlugin { definitions: [Object] } ],
  mode: 'development',
  devtool: '#cheap-module-eval-source-map',
  watch: true 
}

step3: dev config uses webpack-merge to return a dev config by merging with a common config
    // file: ./React/webpack.config.dev.js
    // const merge = require("webpack-merge");
    // const common = require("./webpack.common.js");
    // ..
    // const rv = merge(common, {
    //     mode: "development",
    //     devtool: "#cheap-module-eval-source-map",
    //     watch: true,
    //     plugins: [
    //         new webpack.DefinePlugin({
    //             "process.env": {
    //                 NODE_ENV: JSON.stringify("development"),
    //             },
    //             "PRODUCTION": JSON.stringify(false),
    //             "__DEV__": JSON.stringify(true),
    //         }),
    //     ],

common config: 
{ 
  name: 'React',
  resolve:
   { extensions: [ '.ts', '.tsx', '.js', '.jsx', 'web.jsx', 'web.js', '.json' ],
     modules: [ 'src', 'node_modules' ],
  node: { fs: 'empty', net: 'empty', tls: 'empty', vertx: 'empty' },
  stats:
   { all: false,
     colors: true,
     errors: true,
     errorDetails: false,
     warnings: true,
     timings: true,
     chunks: true,
     chunkOrigins: false,
     entrypoints: true,
     depth: false,
     reasons: false,
     source: false,
     moduleTrace: false,
     warningsFilter:
      [ /WARNING in \./g,
        /export 'IValidation' was not found in '_types\/IValidation'/g,
        /export 'FormField' was not found in '\.\/form-model'/g,
        'dummy string' ] },
  entry:
   { app:
      [ .\\React\\src\\_entry\\app' ],
     bundle1:
      [ .\\React\\src\\_entry\\bundle1' ],
     bundle2:
      [ .\\React\\src\\_entry\\bundle2' ],
     bundle3:
      [ .\\React\\src\\_entry\\bundle3' ],
     bundle4:
      [ .\\React\\src\\_entry\\bundle4' ],
     bundle5:
      [ .\\React\\src\\_entry\\bundle5' ] },
  output:
   { path: .\\dist\\react',
     publicPath: 'React/',
     filename: '[name].js',
     chunkFilename: '[name].js' },
  module: { rules: [ [Object], [Object], [Object], [Object] ] },
  plugins:
   [ CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     NoEmitOnErrorsPlugin {},
     WebpackCleanupPlugin { options: [Object] },
     WatchIgnorePlugin { paths: [Array] },
     ForkTsCheckerWebpackPlugin {
       options: {},
       tsconfig: './tsconfig.json',
       tslint: undefined,
       watch: [],
       ignoreDiagnostics: [],
       ignoreLints: [],
       logger: [Object],
       silent: false,
       async: true,
       checkSyntacticErrors: false,
       workersNumber: 1,
       memoryLimit: 2048,
       useColors: true,
       colors: [Object],
       formatter: [Function: defaultFormatter],
       tsconfigPath: undefined,
       tslintPath: undefined,
       watchPaths: [],
       compiler: undefined,
       started: undefined,
       elapsed: undefined,
       cancellationToken: undefined,
       isWatching: false,
       checkDone: false,
       compilationDone: false,
       diagnostics: [],
       lints: [],
       emitCallback: [Function: noopEmitCallback],
       doneCallback: [Function: doneCallback],
       typescriptVersion: '2.8.3',
       tslintVersion: undefined,
       vue: false },
     MiniCssExtractPlugin { options: [Object] },
     DllReferencePlugin { options: [Object] },
     IgnorePlugin {
       resourceRegExp: /vertx/,
       contextRegExp: undefined,
       checkIgnore: [Function: bound checkIgnore] } ] 
}

dev config (which is created by using webpack-merge as above for just a couple of tweaks to common config):
{ 
  name: 'React',
  resolve:
   { extensions: [ '.ts', '.tsx', '.js', '.jsx', 'web.jsx', 'web.js', '.json' ],
     modules: [ 'src', 'node_modules' ],
  node: { fs: 'empty', net: 'empty', tls: 'empty', vertx: 'empty' },
  stats:
   { all: false,
     colors: true,
     errors: true,
     errorDetails: false,
     warnings: true,
     timings: true,
     chunks: true,
     chunkOrigins: false,
     entrypoints: true,
     depth: false,
     reasons: false,
     source: false,
     moduleTrace: false,
     warningsFilter:
      [ /WARNING in \./g,
        /export 'IValidation' was not found in '_types\/IValidation'/g,
        /export 'FormField' was not found in '\.\/form-model'/g,
        'dummy string' ] },
  entry:
   { app:
      [ .\\React\\src\\_entry\\app' ],
     bundle1:
      [ .\\React\\src\\_entry\\bundle1' ],
     bundle2:
      [ .\\React\\src\\_entry\\bundle2' ],
     bundle3:
      [ .\\React\\src\\_entry\\bundle3' ],
     bundle4:
      [ .\\React\\src\\_entry\\bundle4' ],
     bundle5:
      [ .\\React\\src\\_entry\\bundle5' ] },
  output:
   { path: .\\dist\\react',
     publicPath: 'React/',
     filename: '[name].js',
     chunkFilename: '[name].js' },
  module: { rules: [ [Object], [Object], [Object], [Object] ] },
  plugins:
   [ CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
     NoEmitOnErrorsPlugin {},
     WebpackCleanupPlugin { options: [Object] },
     WatchIgnorePlugin { paths: [Array] },
     ForkTsCheckerWebpackPlugin {
       options: {},
       tsconfig: './tsconfig.json',
       tslint: undefined,
       watch: [],
       ignoreDiagnostics: [],
       ignoreLints: [],
       logger: [Object],
       silent: false,
       async: true,
       checkSyntacticErrors: false,
       workersNumber: 1,
       memoryLimit: 2048,
       useColors: true,
       colors: [Object],
       formatter: [Function: defaultFormatter],
       tsconfigPath: undefined,
       tslintPath: undefined,
       watchPaths: [],
       compiler: undefined,
       started: undefined,
       elapsed: undefined,
       cancellationToken: undefined,
       isWatching: false,
       checkDone: false,
       compilationDone: false,
       diagnostics: [],
       lints: [],
       emitCallback: [Function: noopEmitCallback],
       doneCallback: [Function: doneCallback],
       typescriptVersion: '2.8.3',
       tslintVersion: undefined,
       vue: false },
     MiniCssExtractPlugin { options: [Object] },
     DllReferencePlugin { options: [Object] },
     IgnorePlugin {
       resourceRegExp: /vertx/,
       contextRegExp: undefined,
       checkIgnore: [Function: bound checkIgnore] },
     DefinePlugin { definitions: [Object] } ],
  mode: 'development',
  devtool: '#cheap-module-eval-source-map',
  watch: true 
}

...

Starting type checking service...
Using 1 worker with 2048MB memory limit

webpack is watching the files…

[at-loader] Using typescript@2.8.3 from typescript and "tsconfig.json" from ./tsconfig.json (in a forked process).

Warning: The 'no-boolean-literal-compare' rule requires type information.
ts-loader: Using typescript@2.8.3 and .\React\tsconfig.json

[at-loader] Checking started in a separate process...

WebpackCleanupPlugin: 0 file(s) deleted.

[at-loader] Ok, 2.503 sec.

WebpackCleanupPlugin: 0 file(s) deleted.
No type errors found
Version: typescript 2.8.3
Time: 7152ms

... webpack output listing bundles, etc. ...
```

**Comment by domehead100** [comment]
I have to get some sleep, early meeting in the morning, but I'll try tomorrow or tomorrow night not using merge at all and see how that plays out.  If it still throws the error in question, I'll try not exporting multiple configs from the first step and see how that works out.

I'll try to let you know the results in the next 24 hours or so.

**Comment by ev1stensberg** [comment]
@domehead100 Gotcha, nizenize. I use webpack merge at work, and when using nested objects then not all props would get exported. Hmu when you're ready 👍

**Comment by domehead100** [comment]
Turns out that taking out webpack-merge doesn't fix the issue.  Still get the error shown down at the bottom of this post if exporting multiple configs from the root webpack.config.js with or without webpack-merge.  If I leave webpack-merge in and export only a single config, I don't get the error.  So, it seems that exporting multiple configs is what causes the error.

What's really a bummer is that the --info-verbosity is actually not useful for what I was wanting, which is that while in watch mode I was hoping to see:

- print "Compilation starting.."
- print the output, such as chunks but also more importantly any errors or warnings from loaders, linters, etc.
- print "Compilation finished"

Thus, any errors or warnings would show up between the two phrases and would be parsed by a vscode problem matcher if I run the build in a vscode task, allowing me to see the count of problems and to navigate to the exact line number of each via a mouse click.

Instead, what I get is:
- print "Compilation starting..."
- print "Compilation finished"
- print the output (including chunks, warnings, and errors)

Because the output is not between the magic phrases, it won't work with a vscode problem matcher.  Looks like I'll be able to use "Type checking in progress.." and "Time: /d+/ms" for the magic phrases without info-verbosity.

I'm kind of wondering what the point of --info-verbosity is at this point.

Anyway, here is the error when exporting multiple configs with --info-verbosity verbose.  Should have included the entire call stack in the original issue (sorry):

```javascript

C:\Project\node_modules\webpack-cli\bin\cli.js:464
                                compiler.hooks.beforeCompile.tap("WebpackInfo", compilation => {
                                 ^
TypeError: Cannot read property 'tap' of undefined
    at processOptions (C:\Project\node_modules\webpack-cli\bin\cli.js:464:34)
    at yargs.parse (C:\Project\node_modules\webpack-cli\bin\cli.js:528:3)
    at Object.parse (C:\Project\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
    at C:\Project\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Project\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by ev1stensberg** [comment]
Do you mind if I get back to you this weekend? Got full time job to prioritize and this seems like it needs investigation 🙃

**Comment by domehead100** [comment]
No worries.  Actually I've determined that I don't need the --info-verbosity setting at all (since it doesn't do quite what I thought it did).

**Comment by ev1stensberg** [comment]
Alright.
