### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by wedog** [webpack/webpack-cli#609]
**Describe the bug**
missing option: “/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,”
from the webpack@4.20.0 ,the "schemas/WebpackOptions.json" file dose not exist  “optionsSchema.definitions.output.properties.path.description”

**What is the current behavior?**

/home/gitlab-runner/builds/a0472af4/0/ne-fe/ne-oa-dashboard/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,		                                           

**To Reproduce**
Version compatibility

**Expected behavior**
no error

**Screenshots**

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/gitlab-runner/builds/a0472af4/0/ne-fe/ne-oa-dashboard/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/gitlab-runner/builds/a0472af4/0/ne-fe/ne-oa-dashboard/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/gitlab-runner/builds/a0472af4/0/ne-fe/ne-oa-dashboard/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Additional context**
Add any other context about the problem here like linking to an similar issue you might think is the cause.

**Comment by ev1stensberg** [comment]
Which webpack-cli version are you running?

**Comment by ev1stensberg** [comment]
Update to `webpack-cli v.3.1.1`
