### ISSUE TITLE
Migrate: Plugins defined in variable results in TypeError

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack-cli#69]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
I've declared plugins in a variable to be able to add extra plugins for production build (like `UglifyJsPlugin`), this results in:
```
node_modules/.bin/webpack-cli --migrate webpack.config.js
<path>/node_modules/webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js:21
		.filter(path => path.parent.value.key.name === 'plugins')
		                                     ^

TypeError: Cannot read property 'name' of undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Webpack config:
```
const webpack = require('webpack');

let plugins = [
  new webpack.DefinePlugin({
    alwaysTrue: true
  })
];

module.exports = {
  entry: {
    'app': './src/index.js'
  },
  output: {
    path: 'dist',
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        query: {
          presets: ['env']
        }
      },
    ]
  },
  devtool: 'source-map',
  plugins: plugins
};
```

**What is the expected behavior?**
Be able to define a separate variable where plugins are specified.

**If this is a feature request, what is motivation or use case for changing the behavior?**
To have one config for different builds, where extra plugins are added for specific builds, then it's probably a common use case to define plugins in an array.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
MacOS
node v7.4.0
webpack-cli: `https://github.com/webpack/webpack-cli.git#a46edbb10e443a0e256038212d4f44042c8e1dc2`

**Comment by ev1stensberg** [comment]
Could you post a screenshot of stacktrace in console?

**Comment by jouni-kantola** [comment]
@ev1stensberg, full output below:
```
> node_modules/.bin/webpack-cli --migrate webpack.config.js
/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js:21
		.filter(path => path.parent.value.key.name === 'plugins')
		                                     ^

TypeError: Cannot read property 'name' of undefined
    at ast.find.filter.path (/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js:21:40)
    at Array.filter (native)
    at Collection.filter (/dev/webpack-output-by-build-type/node_modules/jscodeshift/dist/Collection.js:65:46)
    at module.exports (/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js:21:4)
    at transforms.forEach.f (/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/transformations/index.js:40:26)
    at Array.forEach (native)
    at transform (/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/transformations/index.js:40:13)
    at module.exports (/dev/webpack-output-by-build-type/node_modules/webpack-cli/lib/migrate.js:9:23)
    at Object.<anonymous> (/dev/webpack-output-by-build-type/node_modules/webpack-cli/bin/webpack.js:171:30)
    at Module._compile (module.js:571:32)
```

**Comment by pksjce** [comment]
Hi fixed this with #75

**Comment by jouni-kantola** [comment]
@pksjce: I retested with #https://github.com/webpack/webpack-cli/commit/37a594d0346f51c5d62779f835e2293602359a5f. No errors now. I guess this can be closed.

**Comment by ev1stensberg** [comment]
@jouni-kantola Ping us if you got any other issues, we're happy to help 🎉  Closed.
