### ISSUE TITLE
Bug: "webpack-cli init" errors when trying to install @webpack-cli/init

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack-cli#741]
**Describe the bug**

I tried to run `webpack-cli init` without having the separate init module installed, which makes webpack-cli inform me that there is a new module for that, and asks me whether it should install that. Saying "yes" leads to the following error:

```
i:\temp\mj>npx webpack-cli init
npx: installed 1 in 1.133s
Path must be a string. Received undefined
i:\temp\mj\node_modules\webpack-cli\bin\cli.js
The command moved into a separate package: @webpack-cli/init
Would you like to install init? (That will run npm install -g @webpack-cli/init) (yes/NO)yes
{ Error: Cannot find module 'i:\temp\mj\node_modules\@webpack-cli\init'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (i:\temp\mj\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at runCommand.then.result (i:\temp\mj\node_modules\webpack-cli\bin\prompt-command.js:94:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

If I install `@webpack-cli/init` manually (and without `-g`, haven't tried with) then that error does not occur.

**Comment by rishabh3112** [comment]
Thanks, @Pomax for reporting. It should be fixed soon.

**Comment by ematipico** [comment]
PR merged, next release will contain the fix!

**Comment by Pomax** [comment]
sweet, many thanks!
