### ISSUE TITLE
Enh: `--config-register` not resolved relative to `process.pwd()`

### ISSUE THREAD

**Issue by Swatinem** [webpack/webpack-cli#746]
**Describe the bug**

the `--config-register / -r` flag differs from the `-r` flag of `node` which is confusing. In particular relative paths are not resolved relative to `process.pwd()`

**What is the current behavior?**

    $ webpack -r ./tools/register.js --config packages/xxx/tools/webpack.config

That fails with

> Error: Cannot find module './tools/register.js'

**To Reproduce**

* **fails**: `webpack -r ./tools/register.js --config packages/xxx/tools/webpack.config`
* **succeeds**: `webpack -r $(pwd)/tools/register.js --config packages/xxx/tools/webpack.config`
* **succeeds**: `node -r ./tools/register.js node_modules/.bin/webpack --config packages/xxx/tools/webpack.config`

**Expected behavior**

The behavior of `-r` should match the behavior of `node`, in particular that relative paths are resolved relative to `process.pwd()`.

**Comment by evenstensberg** [comment]
Oh didn't know, do you mind submitting a PR for this?

**Comment by Swatinem** [comment]
> do you mind submitting a PR for this?

Can do, give me some time :-)

**Comment by jamesgeorge007** [comment]
@evenstensberg I would gladly take this up :+1: It would be great if you could give me a better picture of the files to be worked with as I'm not that aware of the code-base.

**Comment by evenstensberg** [comment]
Great, hmu if you have any questions! @Swatinem since this hasn't had activity since January, I'll let @jamesgeorge007 do this

**Comment by jamesgeorge007** [comment]
@evenstensberg Can you point me to the files to work with :thinking:

**Comment by Swatinem** [comment]
Go for it. I completely forgot about this…

**Comment by evenstensberg** [comment]
Here you go: https://github.com/webpack/webpack-cli/blob/master/bin/utils/convert-argv.js#L106-L120

**Comment by jamesgeorge007** [comment]
@evenstensberg It seems that this is the required workaround :-
```js
return require(path.resolve(process.cwd(), configPath));
```
This is what I infer from the context. Shall I propose a PR with the respective changes :thinking:

**Comment by evenstensberg** [comment]
Do that!

**Comment by stephtr** [comment]
Is this really fixed? Shouldn't `path.resolve` be added to [line 111](https://github.com/webpack/webpack-cli/pull/903/files#diff-f28fd412eca1697c5b34e761c9bbd562R111)?

**Comment by evenstensberg** [comment]
Could someone open a PR? Thanks for pointing it out

**Comment by stephtr** [comment]
`path.resolve` was wrong, that way scripts from dependencies wouldn't be resolved. Additionally it should be covered by [line 109](https://github.com/webpack/webpack-cli/pull/903/files#diff-f28fd412eca1697c5b34e761c9bbd562R109) (which by the way doesn't include the `node_modules` folder at a higher level).
I still haven't any clue why it fails for me (the relative path passed to `require` in line 111 exists in `module.paths`, but `require` fails nevertheless), but I will take a look at it with a minimal reproducible example.

**Comment by jamesgeorge007** [comment]
@evenstensberg @stephtr what needs to be done further :thinking:

**Comment by stephtr** [comment]
I have just created an example repo: [stephtr/webpack-error](https://github.com/stephtr/webpack-error). It just consists of `webpack` and `webpack-cli` and two more or less empty files `src.js` and `test.js`.
Calling `webpack -r test.js --mode development` loads the test file, while calling `webpack -r ./test.js --mode development` (note the `./`) results in:
```
C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Cannot find module './test.js'
Require stack:
- C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\cli.js
- C:\Users\stroy\Projekte\webpack-error\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (C:\Users\stroy\Projekte\webpack-error\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js:112:7
    at Array.forEach (<anonymous>)
    at WEBPACK_OPTIONS (C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js:111:26)
    at requireConfig (C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js:118:6)
    at C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js:125:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\utils\convert-argv.js:123:15)
    at C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\stroy\Projekte\webpack-error\node_modules\yargs\yargs.js:567:18)
    at C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\stroy\Projekte\webpack-error\node_modules\webpack-cli\bin\cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\stroy\Projekte\webpack-error\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Digging a bit deeper shows that `module.paths` contains the project's root directory, but `require('./test.js');` nevertheless fails.
