### ISSUE TITLE
webpack@alpha is broken against webpack-cli@latest

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack-cli#762]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3408176/52923802-60393080-32de-11e9-9a93-2b453a873fd9.png)

```bash
Done in 4.37s.
➜  v5-webpack yarn webpack
yarn run v1.5.1
(node:11347) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning package.json: No license field
$ /mnt/c/Users/Administrator/Code/v5-webpack/node_modules/.bin/webpack
/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:492
        } else if (stats.hash !== lastHash) {
                         ^

TypeError: Cannot read property 'hash' of undefined
    at compilerCallback (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:492:26)
    at AsyncParallelHook.eval [as callAsync] (eval at create (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncParallelHook.lazyCompileHook (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Cache.shutdown (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack/lib/Cache.js:75:23)
    at Compiler.close (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack/lib/Compiler.js:696:14)
    at processOptions (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:533:38)
    at yargs.parse (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:537:5)
    at Object.parse (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/yargs/yargs.js:567:18)
    at /mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:219:9
    at Object.<anonymous> (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack-cli/bin/cli.js:539:3)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/c/Users/Administrator/Code/v5-webpack/node_modules/webpack/bin/webpack.js:153:2)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
error An unexpected error occurred: "Command failed.
```
**Additional context**
PR Incoming

**Comment by evenstensberg** [comment]
You're the best bro
