### ISSUE TITLE
needs investigation: packages/webpack-scaffold : Test failing

### ISSUE THREAD

**Issue by pranshuchittora** [webpack/webpack-cli#787]
**Describe the bug**
Test Failing
```
npm run test

> @webpack-cli/webpack-scaffold@0.1.3 test /home/wasd/webpack/webpack-cli/packages/webpack-scaffold
> jest --detectOpenHandles

 FAIL  __tests__/index.test.js
  ● Test suite failed to run

    SyntaxError: /home/wasd/webpack/webpack-cli/packages/webpack-scaffold/index.ts: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (3:8):

      1 | import * as jscodeshift from "jscodeshift";
      2 | 
    > 3 | export interface IInquirerScaffoldObject {
        |        ^
      4 | 	type?: string;
      5 | 	name: string;
      6 | 	message: string;

    Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.

      at Parser.raise (../../node_modules/@babel/parser/lib/index.js:3831:17)
      at Parser.expectPlugin (../../node_modules/@babel/parser/lib/index.js:5148:18)
      at Parser.maybeParseExportDefaultSpecifier (../../node_modules/@babel/parser/lib/index.js:8313:12)
      at Parser.parseExport (../../node_modules/@babel/parser/lib/index.js:8265:29)
      at Parser.parseStatementContent (../../node_modules/@babel/parser/lib/index.js:7347:27)
      at Parser.parseStatement (../../node_modules/@babel/parser/lib/index.js:7243:17)
      at Parser.parseBlockOrModuleBlockBody (../../node_modules/@babel/parser/lib/index.js:7810:25)
      at Parser.parseBlockBody (../../node_modules/@babel/parser/lib/index.js:7797:10)
      at Parser.parseTopLevel (../../node_modules/@babel/parser/lib/index.js:7181:10)
      at Parser.parse (../../node_modules/@babel/parser/lib/index.js:8660:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.19s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webpack-cli/webpack-scaffold@0.1.3 test: `jest --detectOpenHandles`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @webpack-cli/webpack-scaffold@0.1.3 test script.

```

**What is the current behavior?**
It should pass with flying colors. 

**To Reproduce**
```
cd packages/webpack-saffold
npm run test
```
CC @evenstensberg

**Comment by pranshuchittora** [comment]
Working :tada:
