### ISSUE TITLE
webpack-cli fails to install due to node ./bin/opencollective.js failing

### ISSUE THREAD

**Issue by srchulo** [webpack/webpack-cli#889]
**Describe the bug**

Installing webpack-cli@3.3.2 fails with this error:

```
npm ERR! Linux 4.9.75-ts1
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

stack Error: webpack-cli@3.3.2 postinstall: `node ./bin/opencollective.js`
stack Exit status 1                                              
stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
stack     at emitTwo (events.js:87:13)                           
stack     at EventEmitter.emit (events.js:172:7)                 
stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
stack     at emitTwo (events.js:87:13)                           
stack     at ChildProcess.emit (events.js:172:7)                 
at maybeClose (internal/child_process.js:818:16)            
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Specifically, this command:

`node ./bin/opencollective.js `

**What is the current behavior?**

The install fails.

**To Reproduce**
1. Install webpack globally.
2. Install webpack-cli@3.3.2

**Expected behavior**
webpack-cli@3.3.2 should successfully install.

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
I can't because webpack-cli is not installed.

**Additional context**
I have webpack installed globally, and this may be related to why it isn't fixed for me, but was fixed here:

https://github.com/webpack/webpack-cli/issues/878

**Comment by srchulo** [comment]
I also get an in issue in bin/opencollective.js on line 12:

https://github.com/webpack/webpack-cli/blob/master/bin/opencollective.js#L12

```
function print(str = "", color = "dim") {
                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by misterdev** [comment]
I see you are using node v4, you should update it to the current version `>=10`.

Node <=6 has been discontinued as you can see [here](https://nodejs.org/en/about/releases/)

**Comment by srchulo** [comment]
Thanks! That seems to have fixed my issue.

**Comment by mac25** [comment]
Got this error 
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- C:\Users\Admin\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\webpack-dev-server\bin\webpack-dev-server.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
