### ISSUE TITLE
[BUG]: 🐞init throws "A name parameter is required to create a storage"

### ISSUE THREAD

**Issue by misterdev** [webpack/webpack-cli#901]
**Describe the bug**

Executing `webpack-cli init` in a folder where there is a `package.json` results in an unclear error

**What is the current behavior?**

```
webpack-cli init
assert.js:345
    throw err;
    ^

AssertionError [ERR_ASSERTION]: A name parameter is required to create a storage
    at new Storage (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-generator/lib/util/storage.js:24:5)
    at InitGenerator._getStorage (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-generator/lib/index.js:618:12)
    at new Generator (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-generator/lib/index.js:148:24)
    at new InitGenerator (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/@webpack-cli/generators/init-generator.js:23:9)
    at Environment.instantiate (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-environment/lib/environment.js:429:12)
    at Environment.create (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-environment/lib/environment.js:407:17)
    at Environment.run (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/yeoman-environment/lib/environment.js:464:28)
    at Object.modifyHelperUtil [as default] (/usr/local/lib/node_modules/@webpack-cli/init/node_modules/@webpack-cli/utils/modify-config-helper.js:59:9)
    at initializeInquirer (/usr/local/lib/node_modules/@webpack-cli/init/index.js:19:46)
    at runWhenInstalled (/Users/devid/Workspace/OSS/testlog/node_modules/webpack-cli/bin/utils/prompt-command.js:46:9)
```

**To Reproduce**
This error occurs if you try to run webpack-cli init on a project that has already been bootstrapped. We need to support bootstrapping multiple times, run the init command two times.

**Expected behavior**
I expect it to work unless I already have a `webpack.config.js` in the same folder. Anyway it should give a more clear error

Up for grabs

**Comment by anikethsaha** [comment]
Its working fine with me. 
the senerios I tested
- With `package.json` present alone
- With `webpack.config.js` present alone
- With both present
It is working in my system. Is there any other step to reproduce it .

**Comment by evenstensberg** [comment]
@misterdev record on yoututbe and put out a link if you can. Also, focus on your gsoc proposal ;)

**Comment by evenstensberg** [comment]
This error occurs if you try to run `webpack-cli init` on a project that has already been bootstrapped. We need to support bootstrapping multiple times, run the init command two times. Up for grabs

**Comment by anikethsaha** [comment]
I am facing this now!  
Getting this even running the `npx webpack-cli init` twice still the same. I actually didn't get this why it's happening?

cc @evenstensberg

**Comment by evenstensberg** [comment]
Probbaly cause files are already there when running twice

**Comment by anikethsaha** [comment]
> Probbaly cause files are already there when running twice

yeah thats what....cant we check in `init` command befor running it that whether its there or not and if its there then show the message or delete it....befor generating

**Comment by evenstensberg** [comment]
I don't know, you'll need to do some research and prove it works

**Comment by anikethsaha** [comment]
> to do some research and prove it works

yeah sure! I will do it by the weekend ! 👍

**Comment by caogaofeng0** [comment]
Its working fine with me
touch package.json
